In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("wiki_movie_plots_deduped.csv")
df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...

In [6]:
df.dtypes

Release Year         int64
Title               object
Origin/Ethnicity    object
Director            object
Cast                object
Genre               object
Wiki Page           object
Plot                object
dtype: object

In [7]:
new_df = df[df['Release Year'] > 2000]
new_df.shape

(12093, 8)

In [8]:
new_df.Genre.nunique()

1571

In [9]:
true_genre_count = new_df['Genre'].str.split(', ').explode().nunique()
print(f"True Unique Genres: {true_genre_count}")

True Unique Genres: 999

In [10]:
print(new_df.Genre.isna().sum())
print(new_df.duplicated().sum())

0
0

In [11]:
new_df.Genre.value_counts().head(10)

Genre
unknown            2304
drama              1603
comedy             1115
romance             583
action              528
thriller            440
horror              424
romantic comedy     215
comedy-drama        128
crime drama         127
Name: count, dtype: int64

In [13]:
new_df = new_df[~(new_df['Genre'] == 'unknown')]

In [14]:
new_df.Genre.value_counts().head(40)

Genre
drama               1603
comedy              1115
romance              583
action               528
thriller             440
horror               424
romantic comedy      215
comedy-drama         128
crime drama          127
science fiction      108
animation            100
anime                 88
fantasy               80
comedy, drama         75
action thriller       69
family                60
crime                 57
documentary           49
romantic drama        46
adventure             45
drama, romance        44
crime thriller        43
superhero             43
war                   39
action comedy         38
romance, drama        33
comedy/drama          31
comedy drama          31
romance/comedy        30
action, thriller      29
action drama          29
action, romance       29
comedy, romance       28
comedy / romance      28
                      28
black comedy          27
drama                 27
musical               27
horror comedy         27
romance, comedy       26
Name: count, dtype: int64

In [15]:
new_df['Genre'] = new_df['Genre'].astype(str).str.strip()

In [12]:
new_df.Genre.value_counts().head(40)

Genre
drama               1630
comedy              1134
romance              600
action               549
thriller             458
horror               429
romantic comedy      219
comedy-drama         128
crime drama          127
science fiction      108
animation            101
anime                 88
fantasy               80
comedy, drama         77
action thriller       75
family                60
crime                 57
drama, romance        52
documentary           49
romantic drama        46
adventure             46
superhero             43
crime thriller        43
war                   39
action comedy         38
romance, drama        33
comedy drama          32
comedy, romance       31
action, romance       31
comedy/drama          31
romance/comedy        30
drama, thriller       29
action drama          29
action, thriller      29
comedy / romance      28
                      28
horror comedy         27
black comedy          27
musical               27
biography             26
Name: count, dtype: int64

In [13]:
new_df['Genre'] = new_df['Genre'].astype(str).str.strip()

# 2. Create a mask where the string is strictly a single alphabetical word
single_word_mask = new_df['Genre'].str.isalpha()

# 3. Apply the mask to get your clean rows
single_genre_df = new_df[single_word_mask]

In [14]:
single_genre_df.Genre.value_counts().head(40)

Genre
drama           1630
comedy          1134
romance          600
action           549
thriller         458
horror           429
animation        101
anime             88
fantasy           80
family            60
crime             57
documentary       49
adventure         46
superhero         43
war               39
musical           27
biography         26
dramedy           24
social            21
mockumentary      20
tokusatsu         19
biopic            18
masala            16
animated          14
mystery           13
western           11
sports            10
historical         9
biographical       8
children           7
satire             7
love               6
romantic           5
political          5
disaster           5
parody             5
docudrama          5
suspense           4
supernatural       4
history            4
Name: count, dtype: int64

In [15]:
print(single_genre_df.Plot.isna().sum())
print(single_genre_df.Plot.duplicated().sum())

0
65

In [16]:
duplicated_plots_df = single_genre_df[single_genre_df.Plot.duplicated(keep=False)]

# Sort by the Plot column so duplicates appear next to each other
duplicated_plots_df.sort_values(by='Plot')

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
22251,2010,Wrecked,Canadian,Michael J. Greenspan,"Adrien Brody, Caroline Dhavernas",drama,https://en.wikipedia.org/wiki/Wrecked_(film),"A man, referred to in the movie only as ""Man"" ..."
22289,2011,Wrecked,Canadian,Michael Greenspan,Adrien Brody,thriller,https://en.wikipedia.org/wiki/Wrecked_(film),"A man, referred to in the movie only as ""Man"" ..."
33594,2010,Into the White Night,Japanese,Yoshihiro Fukagawa,"Maki Horikita, Kengo Kora, Eiichiro Funakoshi",crime,https://en.wikipedia.org/wiki/Into_the_White_N...,"A pawn shop owner in Osaka is murdered, but du..."
33628,2011,Into the White Night,Japanese,Yoshihiro Fukagawa,"Maki Horikita, Kengo Kora",drama,https://en.wikipedia.org/wiki/Into_the_White_N...,"A pawn shop owner in Osaka is murdered, but du..."
28063,2009,Black Dalia,Malayalam,Baburaj,"Suresh Gopi, Vani Viswanath, Baburaj",action,https://en.wikipedia.org/wiki/Black_Dalia,A student of Sacred Heart Medical College is f...
...,...,...,...,...,...,...,...,...
31371,2016,Thozha,Tamil,Vamsi Paidipally,"Nagarjuna, Karthi, Tamannaah",drama,https://en.wikipedia.org/wiki/Oopiri,Vikramadhitya is a wealthy entrepreneur who ow...
23717,2014,But Always,Hong Kong,Zou Xian,"Nicholas Tse, Gao Yuanyuan",romance,https://en.wikipedia.org/wiki/But_Always,While most of “But Always” takes place in New ...
22723,2014,But Always,Chinese,Snow Zou,"Nicholas Tse, Gao Yuanyuan, Du Haitao, Alice L...",romance,https://en.wikipedia.org/wiki/But_Always,While most of “But Always” takes place in New ...
20852,2004,Ella Enchanted,British,Tommy O'Haver,"Anne Hathaway, Hugh Dancy",family,https://en.wikipedia.org/wiki/Ella_Enchanted_(...,"Within the kingdom of Emir, in the town of Fre..."
14450,2004,Ella Enchanted,American,Tommy O'Haver,Anne Hathaway,fantasy,https://en.wikipedia.org/wiki/Ella_Enchanted_(...,"Within the kingdom of Emir, in the town of Fre..."

In [17]:
single_genre_df = single_genre_df.drop_duplicates(subset=['Plot'])
print(single_genre_df.Plot.duplicated().sum())

0

In [18]:
single_genre_df.Genre.value_counts().head(10)

Genre
drama        1614
comedy       1129
romance       594
action        537
thriller      453
horror        422
animation     101
anime          87
fantasy        79
family         58
Name: count, dtype: int64

In [19]:
top_genres = single_genre_df['Genre'].value_counts().head(10).index.tolist()
print(top_genres)

['drama', 'comedy', 'romance', 'action', 'thriller', 'horror', 'animation', 'anime', 'fantasy', 'family']

In [20]:
filtered_df = single_genre_df[single_genre_df['Genre'].isin(top_genres)]

# 2. Group by genre and cap each category at a maximum of 500 rows
capped_df = filtered_df.groupby('Genre', group_keys=False).apply(
    lambda x: x.sample(n=min(len(x), 112), random_state=42)
) 

# 3. Check your newly balanced distribution
print(capped_df['Genre'].value_counts())
print(f"\nTotal rows left to scrape: {len(capped_df)}")

Genre
action       112
comedy       112
drama        112
horror       112
romance      112
thriller     112
animation    101
anime         87
fantasy       79
family        58
Name: count, dtype: int64

Total rows left to scrape: 997

C:\Users\Stephen Williams\AppData\Local\Temp\ipykernel_5724\3703743375.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  capped_df = filtered_df.groupby('Genre', group_keys=False).apply(

In [ ]:
capped_df.to_csv("filtered_movie_plots_4000.csv", index=False)

In [21]:
capped_df.shape

(997, 8)

In [22]:
capped_df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
32656,2015,Temper,Telugu,Puri Jagannadh,"N. T. Rama Rao Jr., Kajal Aggarwal, Prakash Raj",action,https://en.wikipedia.org/wiki/Temper_(film),Daya is an orphan who grows up learning that a...
15630,2009,Fighting,American,Dito Montiel,"Channing Tatum, Terrence Howard",action,https://en.wikipedia.org/wiki/Fighting_(2009_f...,Present day New York City: Shawn MacArthur (Ch...
30928,2009,Newtonin Moondram Vidhi,Tamil,Thai Muthuselvam,"S. J. Surya, Sayali Bhagat, Rajiv Krishna\r\n",action,https://en.wikipedia.org/wiki/Newtonin_Moondra...,The film opens with a grim and bearded angry y...
16240,2012,Dark Tide,American,John Stockwell,"Halle Berry, Olivier Martinez, Ralph Brown, Lu...",action,https://en.wikipedia.org/wiki/Dark_Tide,Kate is a shark expert whose business has been...
32469,2011,Shakti,Telugu,Meher Ramesh,"Jr. NTR, Ileana D'Cruz, Manjari Phadnis, Jacki...",action,https://en.wikipedia.org/wiki/Shakti_(2011_film),Aishwarya (Ileana D'Cruz) is the daughter of c...

In [23]:
two_df = capped_df[['Title','Wiki Page']]

for row in two_df.itertuples(index=False):
    title, wiki_page = row
    print(f"Title: {title}, Wiki Page: {wiki_page}")
    break

Title: Temper, Wiki Page: https://en.wikipedia.org/wiki/Temper_(film)

In [26]:
capped_df.to_csv("filtered_movie_plots.csv", index=False)

In [20]:
df = pd.read_csv("wiki_movie_plots_deduped.csv")
df = df[~(df['Genre'] == 'unknown')]
df['Genre'].value_counts().head(10)

Genre
drama        5964
comedy       4379
horror       1167
action       1098
thriller      966
romance       923
western       865
crime         568
adventure     526
musical       467
Name: count, dtype: int64

In [22]:
df['Genre'] = df['Genre'].astype(str).str.strip()


# 2. Create a mask where the string is strictly a single alphabetical word
single_word_mask = df['Genre'].str.isalpha()

# 3. Apply the mask to get your clean rows
single_genre_df = df[single_word_mask]

single_genre_df = single_genre_df.drop_duplicates(subset=['Plot'])
print(single_genre_df.Plot.duplicated().sum())

0

In [23]:
top_genres = single_genre_df['Genre'].value_counts().head(10).index.tolist()
print(top_genres)

['drama', 'comedy', 'horror', 'action', 'thriller', 'romance', 'western', 'crime', 'adventure', 'musical']

In [26]:
single_genre_df.Genre.value_counts().head(10)

Genre
drama        5939
comedy       4374
horror       1154
action       1102
thriller      977
romance       930
western       857
crime         563
adventure     518
musical       464
Name: count, dtype: int64

In [27]:
filtered_df2 = single_genre_df[single_genre_df['Genre'].isin(top_genres)]

# 2. Group by genre and cap each category at a maximum of 500 rows
capped2_df = filtered_df2.groupby('Genre', group_keys=False).apply(
    lambda x: x.sample(n=min(len(x), 400), random_state=42)
)

# 3. Check your newly balanced distribution
print(capped2_df['Genre'].value_counts())

Genre
action       400
adventure    400
comedy       400
crime        400
drama        400
horror       400
musical      400
romance      400
thriller     400
western      400
Name: count, dtype: int64

C:\Users\Stephen Williams\AppData\Local\Temp\ipykernel_23808\1427075391.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  capped2_df = filtered_df2.groupby('Genre', group_keys=False).apply(

In [28]:
print(capped2_df.shape)

(4000, 8)

In [29]:
capped2_df.to_csv('filtered_movie_plots_400Genres.csv', index=False)