In [1]:
import pandas as pd
import numpy as np
import selenium
import urllib.request as request
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import random
import regex as re
import undetected_chromedriver as uc
from selenium.webdriver.common.keys import Keys

In [2]:
df = pd.read_csv("filtered_movie_plots.csv")

In [3]:
df.shape

(997, 8)

In [5]:
df.dtypes

Release Year         int64
Title               object
Origin/Ethnicity    object
Director            object
Cast                object
Genre               object
Wiki Page           object
Plot                object
dtype: object

In [4]:
df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,2015,Temper,Telugu,Puri Jagannadh,"N. T. Rama Rao Jr., Kajal Aggarwal, Prakash Raj",action,https://en.wikipedia.org/wiki/Temper_(film),Daya is an orphan who grows up learning that a...
1,2009,Fighting,American,Dito Montiel,"Channing Tatum, Terrence Howard",action,https://en.wikipedia.org/wiki/Fighting_(2009_f...,Present day New York City: Shawn MacArthur (Ch...
2,2009,Newtonin Moondram Vidhi,Tamil,Thai Muthuselvam,"S. J. Surya, Sayali Bhagat, Rajiv Krishna\r\n",action,https://en.wikipedia.org/wiki/Newtonin_Moondra...,The film opens with a grim and bearded angry y...
3,2012,Dark Tide,American,John Stockwell,"Halle Berry, Olivier Martinez, Ralph Brown, Lu...",action,https://en.wikipedia.org/wiki/Dark_Tide,Kate is a shark expert whose business has been...
4,2011,Shakti,Telugu,Meher Ramesh,"Jr. NTR, Ileana D'Cruz, Manjari Phadnis, Jacki...",action,https://en.wikipedia.org/wiki/Shakti_(2011_film),Aishwarya (Ileana D'Cruz) is the daughter of c...

In [5]:
df = df.rename(columns={'Release Year': 'Release_Year', 'Wiki Page': 'Wiki_Page'})
df.head()

,Release_Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki_Page,Plot
0,2015,Temper,Telugu,Puri Jagannadh,"N. T. Rama Rao Jr., Kajal Aggarwal, Prakash Raj",action,https://en.wikipedia.org/wiki/Temper_(film),Daya is an orphan who grows up learning that a...
1,2009,Fighting,American,Dito Montiel,"Channing Tatum, Terrence Howard",action,https://en.wikipedia.org/wiki/Fighting_(2009_f...,Present day New York City: Shawn MacArthur (Ch...
2,2009,Newtonin Moondram Vidhi,Tamil,Thai Muthuselvam,"S. J. Surya, Sayali Bhagat, Rajiv Krishna\r\n",action,https://en.wikipedia.org/wiki/Newtonin_Moondra...,The film opens with a grim and bearded angry y...
3,2012,Dark Tide,American,John Stockwell,"Halle Berry, Olivier Martinez, Ralph Brown, Lu...",action,https://en.wikipedia.org/wiki/Dark_Tide,Kate is a shark expert whose business has been...
4,2011,Shakti,Telugu,Meher Ramesh,"Jr. NTR, Ileana D'Cruz, Manjari Phadnis, Jacki...",action,https://en.wikipedia.org/wiki/Shakti_(2011_film),Aishwarya (Ileana D'Cruz) is the daughter of c...

In [6]:
def get_movie_revenue_and_budget(driver, release_year,movie_name):
    url = 'https://www.themoviedb.org/'
    driver.get(url)
    time.sleep(random.uniform(1, 4)) 

   # search_box = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "search_v4")))
    formatted_name = movie_name.replace(" ", "%20")
    url = f"https://www.themoviedb.org/search/movie?language=en-US&query={formatted_name}%20y%3A{release_year}"
    driver.get(url)
    time.sleep(random.uniform(2, 4)) 
    # search_box.send_keys(movie_name + " " +"y:"+ str(release_year))
    # time.sleep(random.uniform(1, 4))
    # search_box.send_keys(Keys.ENTER)
    # movies_filter = WebDriverWait(driver, 3).until(
    #             EC.element_to_be_clickable((By.ID, "movie"))
    #         )
    # movies_filter.click()
    # time.sleep(random.uniform(1, 4))
    
    movie_link = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, '//a[@data-media-type="movie"]'))
    )
    
    # 2. Force a native JavaScript browser click (Completely bypasses rendering or coordinate bugs!)
    driver.execute_script("arguments[0].click();", movie_link)
    time.sleep(random.uniform(4, 7)) 
    try:
        revenue_element = driver.find_element(By.XPATH, "//p[strong/bdi[text()='Revenue']]")
        budget_element = driver.find_element(By.XPATH, "//p[strong/bdi[text()='Budget']]")

        revenue = revenue_element.text
        revenue_number = re.sub(r'\D', '', revenue)
        budget = budget_element.text
        budget_number = re.sub(r'\D', '', budget)
        time.sleep(random.uniform(1, 4)) 
    except Exception as e:
        revenue_number = None
        budget_number = None
    return revenue_number, budget_number

In [23]:
two_df = df[['Release_Year','Title']].head(2)
two_df.head()

   Release_Year     Title
0          2015    Temper
1          2009  Fighting

In [ ]:
driver = uc.Chrome(version_main=150, options=uc.ChromeOptions())
scraped_data_matrix = []

for row in two_df.itertuples(index=False):
    release_year, title = row
    try:
        revenue, budget = get_movie_revenue_and_budget(driver,release_year,title)
    except Exception as e:
        revenue, budget = None, None
    driver.refresh()
    time.sleep(5)  # Wait for 5 seconds before the next iteration
    scraped_data_matrix.append([revenue, budget])
    print(f"Scraped data for {title} ({release_year}): Revenue = {revenue}, Budget = {budget}")

driver.quit()
print("Scraping completed.")
print(scraped_data_matrix)

https://www.themoviedb.org/search/movie?language=en-US&query=Temper%20y%3A2015
Title: Temper, Revenue: 11600000, Budget: 5400000
Waiting for 5 seconds before the next iteration...
https://www.themoviedb.org/search/movie?language=en-US&query=Fighting%20y%3A2009
Title: Fighting, Revenue: 32474120, Budget:
Waiting for 5 seconds before the next iteration...
Scraping completed.
[['11600000', '5400000'], ['32474120', '']]

In [27]:
revenue_list = [row[0] for row in scraped_data_matrix]
budget_list = [row[1] for row in scraped_data_matrix]

# 2. Assign them straight to the columns based purely on position order
two_df['Revenue'] = revenue_list
two_df['Budget'] = budget_list
two_df.head()

   Release_Year     Title   Revenue   Budget
0          2015    Temper  11600000  5400000
1          2009  Fighting  32474120

In [8]:
mid = len(df) // 2

# Top half: 498 rows (Indices 0 to 497)
df_part1 = df.iloc[:mid].copy()

# Bottom half: 499 rows (Indices 498 to 996)
df_part2 = df.iloc[mid:].copy()

In [9]:
df_part1.shape, df_part2.shape

((498, 8), (499, 8))

In [34]:
two_df_part2.head(5)

,Release_Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki_Page,Plot
498,2008,Fireflies in the Garden,American,Dennis Lee,"Julia Roberts, Ryan Reynolds, Willem Dafoe, Em...",drama,https://en.wikipedia.org/wiki/Fireflies_in_the...,The story moves back and forth between the ado...
499,2007,Aha!,Bangladeshi,Enamul Kabir Nirjhor,"Humayun Faridi, Tariq Anam Khan, Fazlur Rahman...",drama,https://en.wikipedia.org/wiki/Aha!_(film),Mr. Mallik (Tariq Anam Khan) lives in an about...
500,2010,The Hangman,Bollywood,Vishal Bhandari,"Om Puri, Shreyas Talpade, Gulshan Grover, Smit...",drama,https://en.wikipedia.org/wiki/The_Hangman_(201...,"The Hangman, starring internationally acclaime..."
501,2014,Jamesy Boy,American,Trevor White,Spencer Lofranco\r\nMary-Louise Parker\r\nTais...,drama,https://en.wikipedia.org/wiki/Jamesy_Boy,"James Burns is in prison for selling guns, dru..."
502,2011,Funkytown,Canadian,Daniel Roby,"Patrick Huard, Raymond Bouchard, Geneviève Bro...",drama,https://en.wikipedia.org/wiki/Funkytown_(film),"Set in Montreal during the disco era, the film..."

In [42]:
df_part1['Title'] = df_part1['Title'].str.strip()

In [ ]:
driver = uc.Chrome(version_main=152, options=uc.ChromeOptions())
two_df_part1 = df_part1[['Release_Year','Title']]
scraped_data_matrix = []

for row in two_df_part1.itertuples(index=False):
    release_year, title = row
    try:
        revenue, budget = get_movie_revenue_and_budget(driver,release_year,title)
    except Exception as e:
        revenue, budget = None, None
    time.sleep(5)  # Wait for 5 seconds before the next iteration
    scraped_data_matrix.append([revenue, budget])
    print(f"Scraped data for {title} ({release_year}): Revenue = {revenue}, Budget = {budget}")

driver.quit()
print("Scraping completed.")

Scraped data for Temper (2015): Revenue = 11600000, Budget = 5400000
Scraped data for Fighting (2009): Revenue = 32474120, Budget =
Scraped data for Newtonin Moondram Vidhi (2009): Revenue = , Budget =
Scraped data for Dark Tide (2012): Revenue = 432274, Budget = 25000000
Scraped data for Shakti (2011): Revenue = , Budget =
Scraped data for Machete (2010): Revenue = 45491656, Budget = 10500000
Scraped data for Police Police (2010): Revenue = , Budget =
Scraped data for Tins (2007): Revenue = , Budget =
Scraped data for Expendables 2, TheThe Expendables 2 (2012): Revenue = 314975955, Budget = 100000000
Scraped data for Gandedhe (2010): Revenue = None, Budget = None
Scraped data for Ballistic: Ecks vs. Sever (2002): Revenue = 19924033, Budget = 70000000
Scraped data for Runner (2013): Revenue = 62600000, Budget = 30000000
Scraped data for Shivamani (2003): Revenue = , Budget =
Scraped data for From Paris with Love (2010): Revenue = 52800000, Budget = 52000000
Scraped data for Simhasanam (സിംഹാസനം) (2012): Revenue = , Budget =
Scraped data for Evolusi KL Drift 2 (2010): Revenue = , Budget =
Scraped data for Om 3D (2013): Revenue = , Budget =
Scraped data for Killing Season (2013): Revenue = 39881, Budget =
Scraped data for Wolf Warriors 2 (2017): Revenue = 870325439, Budget = 30100000
Scraped data for Pathfinder (2007): Revenue = 30800000, Budget = 45000000
Scraped data for Black Dalia (2009): Revenue = , Budget =
Scraped data for Police Force: An Inside Story (2004): Revenue = , Budget =
Scraped data for So Close (2002): Revenue = 810243, Budget =
Scraped data for Muniyandi Vilangial Moonramandu (2008): Revenue = , Budget =
Scraped data for Deadly-2 (2010): Revenue = , Budget =
Scraped data for The Fast and the Furious (2001): Revenue = 207283925, Budget = 38000000
Scraped data for Saamida (2008): Revenue = , Budget =
Scraped data for Modhi Vilayadu (2009): Revenue = , Budget =
Scraped data for Half Past Dead (2002): Revenue = 19233280, Budget = 25000000
Scraped data for Sigaram Thodu (2014): Revenue = , Budget =
Scraped data for The Amazing Spider-Man 2 (2014): Revenue = 716934779, Budget = 200000000
Scraped data for Indian (2001): Revenue = , Budget =
Scraped data for Sahasam (2013): Revenue = , Budget =
Scraped data for Aaru (2005): Revenue = , Budget =
Scraped data for Hooked on the Game (2009): Revenue = 3704408, Budget = 3500000
Scraped data for Mr. Nokia (2012): Revenue = , Budget =
Scraped data for Jambhavan (2006): Revenue = , Budget =
Scraped data for Fast & Furious (2009): Revenue = 704709660, Budget = 340000000
Scraped data for Padikathavan (2009): Revenue = , Budget =
Scraped data for Thirupaachi (2005): Revenue = , Budget =
Scraped data for Tracker (2010): Revenue = , Budget = 6500000
Scraped data for Malai Malai (2009): Revenue = , Budget =
Scraped data for Killers (2014): Revenue = , Budget =
Scraped data for Rachcha (2012): Revenue = , Budget =
Scraped data for Thagapansamy (2006): Revenue = , Budget =
Scraped data for Killer Elite (2011): Revenue = 57777106, Budget = 66000000
Scraped data for Mad Max: Fury Road (2015): Revenue = 378858340, Budget = 150000000
Scraped data for Brahmasthram ( ബ്രഹ്മാസ്ത്രം ) (2010): Revenue = None, Budget = None
Scraped data for Valiyavan (2015): Revenue = , Budget =
Scraped data for Wake of Death (2004): Revenue = 521918, Budget = 14000000
Scraped data for Siliconn City (2017): Revenue = , Budget =
Scraped data for Guru (2017): Revenue = , Budget =
Scraped data for Souryam (2008): Revenue = , Budget =
Scraped data for Deuces Wild (2002): Revenue = 6282446, Budget = 10000000
Scraped data for Bravo 5 (2015): Revenue = , Budget =
Scraped data for Plan (2004): Revenue = , Budget =
Scraped data for Marine 3: Homefront, TheThe Marine 3: Homefront (2013): Revenue = , Budget =
Scraped data for Jackie (2010): Revenue = , Budget =
Scraped data for Home of Strangers (2009): Revenue = None, Budget = None
Scraped data for Mrittupuri: Kill Zone (2017): Revenue = None, Budget = None
Scraped data for Singham Returns (2014): Revenue = 26000000, Budget = 13000000
Scraped data for Thavam (2007): Revenue = , Budget =
Scraped data for Game of Death (2010): Revenue = 50000000, Budget = 850000
Scraped data for Quick (2011): Revenue = , Budget =
Scraped data for Crank: High Voltage (2009): Revenue = 34600000, Budget = 20000000
Scraped data for Adda (2013): Revenue = , Budget =
Scraped data for Dammu (2012): Revenue = , Budget =
Scraped data for Mambattiyan (2011): Revenue = , Budget =
Scraped data for Thuppakki (2012): Revenue = 23000000, Budget = 11000000
Scraped data for Inspector Dawood Ibrahim (2016): Revenue = , Budget =
Scraped data for Colombiana (2011): Revenue = 71508440, Budget = 40000000
Scraped data for Kempegowda (2011): Revenue = None, Budget = None
Scraped data for Simha (2010): Revenue = , Budget =
Scraped data for Run Raja Run (2014): Revenue = , Budget =
Scraped data for 12 Rounds (2009): Revenue = 17280326, Budget = 22000000
Scraped data for Sardaar Gabbar Singh (2016): Revenue = , Budget =
Scraped data for Max Payne (2008): Revenue = 85416905, Budget = 35000000
Scraped data for Jai Bolo Telangana (2011): Revenue = , Budget =
Scraped data for Don (2007): Revenue = 15000000, Budget = 5000000
Scraped data for Act of Valor (2012): Revenue = 82499399, Budget = 12000000
Scraped data for Villu (2009): Revenue = , Budget =
Scraped data for Elektra (2005): Revenue = 56681566, Budget = 43000000
Scraped data for Air Collision (2012): Revenue = , Budget = 450000
Scraped data for Fire with Fire (2012): Revenue = 2500277, Budget = 20000000
Scraped data for Driven (2001): Revenue = 54744738, Budget = 94000000
Scraped data for I Spy (2002): Revenue = 51386477, Budget = 70000000
Scraped data for Andhrawala (2004): Revenue = , Budget =
Scraped data for The Recruit (2003): Revenue = 101200000, Budget = 46000000
Scraped data for Ainthaam Padai (2009): Revenue = , Budget =
Scraped data for Mouna Guru (2011): Revenue = 2010000, Budget = 730000
Scraped data for Gabbar Singh (2012): Revenue = 16000000, Budget = 7000000
Scraped data for Rokto (2016): Revenue = , Budget =
Scraped data for American Soldiers (2005): Revenue = None, Budget = None
Scraped data for Thaandavam (2012): Revenue = , Budget =
Scraped data for Biker Boyz (2003): Revenue = 23510601, Budget = 24000000
Scraped data for Kochadaiiyaan (2014): Revenue = , Budget =
Scraped data for Sankharavam (2004): Revenue = None, Budget = None
Scraped data for Undercover Brother (2002): Revenue = 41604473, Budget = 25000000
Scraped data for Vathiyar (2006): Revenue = , Budget =
Scraped data for Apocalypto (2006): Revenue = 120654337, Budget = 40000000
Scraped data for Jil (2015): Revenue = , Budget =
Scraped data for KL Gangster (2011): Revenue = , Budget =
Scraped data for The Hard Corps (2006): Revenue = , Budget = 12000000
Scraped data for 12 Rounds 2: Reloaded (2013): Revenue = , Budget = 4000000
Scraped data for Theekuchi (2008): Revenue = None, Budget = None
Scraped data for Thotta (2008): Revenue = , Budget =
Scraped data for Thee Nagar (2007): Revenue = , Budget =
Scraped data for Secret of the Sultan (2010): Revenue = None, Budget = None
Scraped data for Mister (2017): Revenue = 10748185, Budget =
Scraped data for Singh Saab The Great (2013): Revenue = , Budget =
Scraped data for Rajadhi Raja (2009): Revenue = , Budget =
Scraped data for Striker (2010): Revenue = , Budget =
Scraped data for $9.99 (2008): Revenue = , Budget =
Scraped data for Meet the Robinsons (2007): Revenue = 169332978, Budget = 150000000
Scraped data for Igor (2008): Revenue = 30700000, Budget = 25000000
Scraped data for Kung Fu Panda (2008): Revenue = 632091832, Budget = 130000000
Scraped data for Romeo & Juliet: Sealed with a Kiss (2006): Revenue = 147298761, Budget = 14500000
Scraped data for Ice Age: The Meltdown (2006): Revenue = 660998756, Budget = 80000000
Scraped data for Home on the Range (2004): Revenue = 145358062, Budget = 110000000
Scraped data for Robotech: The Shadow Chronicles (2006): Revenue = , Budget =
Scraped data for Lilo & Stitch (2002): Revenue = 1038027526, Budget = 100000000
Scraped data for Atlantis: The Lost Empire (2001): Revenue = 186053725, Budget = 120000000
Scraped data for Rugrats Go Wild (2003): Revenue = 55443032, Budget = 25000000
Scraped data for Thru the Moebius Strip (2005): Revenue = , Budget = 20000000
Scraped data for The Snow Queen 2: The Snow King (2015): Revenue = None, Budget = None
Scraped data for Barnyard (2006): Revenue = 116755080, Budget = 51000000
Scraped data for The Jungle Book (2016): Revenue = 966550600, Budget = 175000000
Scraped data for Shrek (2001): Revenue = 489676241, Budget = 60000000
Scraped data for Steins;Gate: Fuka Ryōiki no Déjà vu (2013): Revenue = None, Budget = None
Scraped data for Ratchet & Clank (2016): Revenue = 8800000, Budget = 20000000
Scraped data for Return to Never Land (2002): Revenue = 109862682, Budget = 20000000
Scraped data for The Ant Bully (2006): Revenue = 55200000, Budget = 50000000
Scraped data for The Good Dinosaur (2015): Revenue = 332207671, Budget = 175000000
Scraped data for Jumbo (2008): Revenue = , Budget =
Scraped data for Chicken Little (2005): Revenue = 314400000, Budget = 150000000
Scraped data for Open Season (2006): Revenue = 200811689, Budget = 85000000
Scraped data for Space Chimps (2008): Revenue = 64762724, Budget = 37000000
Scraped data for The Wild Thornberrys Movie (2002): Revenue = , Budget = 35000000
Scraped data for Live Freaky! Die Freaky! (2006): Revenue = , Budget =
Scraped data for The Tale of Despereaux (2008): Revenue = 87000000, Budget = 60000000
Scraped data for Jonah: A VeggieTales Movie (2002): Revenue = 25615231, Budget = 14000000
Scraped data for Ivan Tsarevich and the Gray Wolf (2011): Revenue = , Budget =
Scraped data for The Powerpuff Girls Movie (2002): Revenue = 16426471, Budget = 11000000
Scraped data for Once Upon a Time (2013): Revenue = 5380118, Budget = 5000000
Scraped data for Delgo (2008): Revenue = 915840, Budget = 40000000
Scraped data for Pooh's Heffalump Movie (2005): Revenue = 52900000, Budget = 20000000
Scraped data for Happy Feet (2006): Revenue = 384335608, Budget = 100000000
Scraped data for Waking Life (2001): Revenue = 3176880, Budget = 2000000
Scraped data for Shark Bait (2006): Revenue = , Budget =
Scraped data for Chicago 10 (2007): Revenue = 177490, Budget =
Scraped data for Curious George (2006): Revenue = 69834815, Budget = 50000000
Scraped data for The Jungle Book 2 (2003): Revenue = 135700000, Budget = 20000000
Scraped data for Ice Age: Collision Course (2016): Revenue = 408579038, Budget = 105000000
Scraped data for Cars (2006): Revenue = 461983149, Budget = 120000000
Scraped data for Hey Arnold!: The Movie (2002): Revenue = 15249308, Budget = 3000000
Scraped data for Over the Hedge (2006): Revenue = 343397247, Budget = 80000000
Scraped data for WALL-E (2008): Revenue = 521311860, Budget = 180000000
Scraped data for Corpse Bride (2005): Revenue = 118133252, Budget = 40000000
Scraped data for Sinbad: Legend of the Seven Seas (2003): Revenue = 80767884, Budget = 60000000
Scraped data for Geng: The Adventure Begins (2009): Revenue = , Budget =
Scraped data for Team America: World Police (2004): Revenue = 50826898, Budget = 32000000
Scraped data for We Are the Strange (2007): Revenue = , Budget =
Scraped data for The Wild (2006): Revenue = 102338515, Budget = 80000000
Scraped data for Spirit: Stallion of the Cimarron (2002): Revenue = 122563539, Budget = 80000000
Scraped data for Teacher's Pet (2004): Revenue = 6491969, Budget = 10000000
Scraped data for Recess: School's Out (2001): Revenue = 44460850, Budget = 10000000
Scraped data for Piglet's Big Movie (2003): Revenue = 62870546, Budget = 46000000
Scraped data for Free Jimmy (2006): Revenue = 2277607, Budget =
Scraped data for Ice Age (2002): Revenue = 383257136, Budget = 59000000
Scraped data for The Angry Birds Movie (2016): Revenue = 349779543, Budget = 73000000
Scraped data for Eight Crazy Nights (2002): Revenue = 23833131, Budget = 34000000
Scraped data for Horton Hears a Who! (2008): Revenue = 298572799, Budget = 85000000
Scraped data for Everyone's Hero (2006): Revenue = 16627188, Budget = 35000000
Scraped data for McDull, Kung Fu Kindergarten (2009): Revenue = , Budget =
Scraped data for Persepolis (2007): Revenue = 22783990, Budget = 7300000
Scraped data for The Watercolor (2009): Revenue = , Budget =
Scraped data for Happily N'Ever After (2007): Revenue = 38100000, Budget = 47000000
Scraped data for Aqua Teen Hunger Force Colon Movie Film for Theaters (2007): Revenue = 5500000, Budget = 750000
Scraped data for Madagascar: Escape 2 Africa (2008): Revenue = 603900354, Budget = 150000000
Scraped data for A Scanner Darkly (2006): Revenue = 7659918, Budget = 8700000
Scraped data for The Pirates Who Don't Do Anything: A VeggieTales Movie (2008): Revenue = 13247725, Budget = 15000000
Scraped data for TMNT (2007): Revenue = 95608995, Budget = 34000000
Scraped data for Green Days: Dinosaur and I (2011): Revenue = , Budget =
Scraped data for The Secret Life of Pets (2016): Revenue = 875457937, Budget = 75000000
Scraped data for Monster House (2006): Revenue = 140175006, Budget = 75000000
Scraped data for Shrek the Third (2007): Revenue = 808310187, Budget = 160000000
Scraped data for Strawberry Shortcake: The Sweet Dreams Movie (2006): Revenue = , Budget =
Scraped data for Hanuman: Da' Damdaar (2017): Revenue = , Budget =
Scraped data for Ratatouille (2007): Revenue = 623726000, Budget = 150000000
Scraped data for A Christmas Carol (2009): Revenue = 325286646, Budget = 200000000
Scraped data for Bambi II (2006): Revenue = , Budget =
Scraped data for Ribbit (2014): Revenue = , Budget =
Scraped data for The Simpsons Movie (2007): Revenue = 527068851, Budget = 75000000
Scraped data for Bolt (2008): Revenue = 309979994, Budget = 150000000
Scraped data for Blinky Bill the Movie (2015): Revenue = 4634032, Budget = 12800000
Scraped data for Flushed Away (2006): Revenue = 178120010, Budget = 149000000
Scraped data for Robots (2005): Revenue = 262511490, Budget = 75000000
Scraped data for Jimmy Neutron: Boy Genius (2001): Revenue = 80936232, Budget = 25000000
Scraped data for Care Bears: Oopsy Does It! (2007): Revenue = , Budget =
Scraped data for Clifford's Really Big Movie (2004): Revenue = 3255965, Budget = 5000000
Scraped data for Monsters, Inc. (2001): Revenue = 579700000, Budget = 115000000
Scraped data for The SpongeBob SquarePants Movie (2004): Revenue = 141067890, Budget = 30000000
Scraped data for Throne of Elves (2016): Revenue = 3916195, Budget =
Scraped data for Leafie, A Hen Into The Wild (2011): Revenue = 13131714, Budget =
Scraped data for Waltz with Bashir (2008): Revenue = 11179372, Budget = 1500000
Scraped data for Wallace & Gromit: The Curse of the Were-Rabbit (2005): Revenue = 191452, Budget =
Scraped data for Harvie Krumpet (2003): Revenue = , Budget =
Scraped data for Sky Blue (2003): Revenue = , Budget =
Scraped data for Surf's Up (2007): Revenue = 149000000, Budget = 85000000
Scraped data for Star Wars: The Clone Wars (2008): Revenue = 68282844, Budget = 8500000
Scraped data for Treasure Planet (2002): Revenue = 109578115, Budget = 140000000
Scraped data for Inimey Nangathan (2007): Revenue = , Budget =
Scraped data for Bee Movie (2007): Revenue = 287594577, Budget = 150000000
Scraped data for Dragon Ball Z: Battle of Gods (2013): Revenue = 50461371, Budget =
Scraped data for When Marnie Was There (2015): Revenue = 34949567, Budget =
Scraped data for Detective Conan: The Lost Ship in the Sky (2010): Revenue = 36407407, Budget =
Scraped data for Arrietty (2010): Revenue = 149660003, Budget = 23000000
Scraped data for Naruto: Shippūden the Movie (2007): Revenue = 13219807, Budget =
Scraped data for Afterschool Midnighters (2012): Revenue = None, Budget = None
Scraped data for Detective Conan: Jolly Roger in the Deep Azure (2007): Revenue = 22053994, Budget =
Scraped data for Evangelion: 2.0 You Can (Not) Advance (2009): Revenue = 44339362, Budget = 10000000
Scraped data for Naruto the Movie 2: Great Clash! The Illusionary Ruins at the Depths of the Earth (2005): Revenue = None, Budget = None
Scraped data for Gekijō-ban Tiger & Bunny -The Beginning (2012): Revenue = None, Budget = None
Scraped data for Lupin the 3rd vs. Detective Conan: The Movie (2013): Revenue = 41397727, Budget =
Scraped data for Jewelpet the Movie: Sweets Dance Princess (2012): Revenue = , Budget =
Scraped data for Magic Tree House (2012): Revenue = , Budget =
Scraped data for Space Pirate Captain Harlock (2013): Revenue = 18010317, Budget = 30000000
Scraped data for Kaguya-Hime no Monogatari (2013): Revenue = 24366656, Budget = 49300000
Scraped data for Naruto the Movie: Road to Ninja (2012): Revenue = 17876559, Budget =
Scraped data for Naruto Shippūden 4: The Lost Tower (2010): Revenue = 16537336, Budget =
Scraped data for Kaze Tachinu (2013): Revenue = 117932401, Budget = 30000000
Scraped data for Doraemon: Nobita to Kiseki no Shima ~Animal Adventure~ (2012): Revenue = 46180706, Budget =
Scraped data for Evangelion 3.0 (2012): Revenue = 67282623, Budget = 13000000
Scraped data for Evangelion: 1.0 You Are (Not) Alone (2007): Revenue = 20121073, Budget = 7000000
Scraped data for Inazuma Eleven: Saikyō Gundan Ōgre Shūrai (2010): Revenue = 7243674, Budget =
Scraped data for Detective Conan: Quarter of Silence (2011): Revenue = 42808575, Budget =
Scraped data for Doraemon: Nobita's Great Battle of the Mermaid King (2010): Revenue = 34702573, Budget =
Scraped data for 5 Centimeters Per Second (2007): Revenue = 548192, Budget = 5000000
Scraped data for Fairy Tail the Movie: The Phoenix Priestess (2012): Revenue = 911467, Budget =
Scraped data for Poketto Monsutā Adobansu Jenerēshon Myū and the Wave Guiding Hero Rukario (2005): Revenue = None, Budget = None
Scraped data for Pretty Cure All Stars DX3: Deliver the Future! The Rainbow~Colored Flower That Connects the World! (2011): Revenue = , Budget =
Scraped data for King of Thorn (2010): Revenue = , Budget =
Scraped data for Redline (2010): Revenue = , Budget =
Scraped data for Fullmetal Alchemist the Movie: The Sacred Star of Milos (2011): Revenue = 7621364, Budget =
Scraped data for Heaven's Lost Property the Movie: The Angeloid of Clockwork (2011): Revenue = , Budget =
Scraped data for Tetsujin Nijūhachi-gō: Hakuchū no Zangetsu (2007): Revenue = None, Budget = None
Scraped data for Hoshi o Ou Kodomo (2011): Revenue = , Budget =
Scraped data for Phantom Ruler: Zoroark (2010): Revenue = None, Budget = None
Scraped data for xxxHolic: A Midsummer Night's Dream (2005): Revenue = , Budget =
Scraped data for Tekken: Blood Vengeance (2011): Revenue = , Budget =
Scraped data for Library War: The Wings of Revolution (2012): Revenue = , Budget =
Scraped data for Naruto Shippūden 3: Inheritors of the Will of Fire (2009): Revenue = 8100000, Budget =
Scraped data for 009 Re:Cyborg (2012): Revenue = , Budget =
Scraped data for Colorful (2010): Revenue = , Budget =
Scraped data for Hayate the Combat Butler! Heaven Is a Place on Earth (2011): Revenue = , Budget =
Scraped data for Piano no Mori (2007): Revenue = 2014665, Budget =
Scraped data for Book Girl (2010): Revenue = , Budget =
Scraped data for Fullmetal Alchemist the Movie: Conqueror of Shamballa (2005): Revenue = 10197984, Budget =
Scraped data for Arceus Chōkoku no Jikū e (2009): Revenue = 52119081, Budget =
Scraped data for Doraemon: Nobita and the New Steel Troops: ~Angel Wings~ (2011): Revenue = , Budget =
Scraped data for The Girl Who Leapt Through Time (2006): Revenue = 3478290, Budget =
Scraped data for Asura (2012): Revenue = , Budget =
Scraped data for The Princess in the Birdcage Kingdom (2005): Revenue = , Budget =
Scraped data for Strike Witches (2012): Revenue = , Budget =
Scraped data for Welcome to the Space Show (2010): Revenue = , Budget =
Scraped data for ExtremeSpeed Genesect: Mewtwo Awakens (2013): Revenue = 32293377, Budget =

In [ ]:
driver = uc.Chrome(version_main=152, options=uc.ChromeOptions())
revenue, budget = get_movie_revenue_and_budget(driver,2001,"The Fast and the Furious")
print(f"Scraped data for The Fast and the Furious (2001): Revenue = {revenue}, Budget = {budget}")

https://www.themoviedb.org/search/movie?language=en-US&query=The%20Fast%20and%20the%20Furious%20y%3A2001
Scraped data for The Fast and the Furious (2001): Revenue = 207283925, Budget = 38000000

In [40]:
string = " The Fast and the Furious"
print(string.strip())
print(string)

The Fast and the Furious
 The Fast and the Furious

In [51]:
revenue_list = [row[0] for row in scraped_data_matrix]
budget_list = [row[1] for row in scraped_data_matrix]

# 2. Assign them straight to the columns based purely on position order
two_df_part1['Revenue'] = revenue_list
two_df_part1['Budget'] = budget_list
two_df_part1.head()

C:\Users\Stephen Williams\AppData\Local\Temp\ipykernel_16816\2717512443.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  two_df_part1['Revenue'] = revenue_list
C:\Users\Stephen Williams\AppData\Local\Temp\ipykernel_16816\2717512443.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  two_df_part1['Budget'] = budget_list

   Release_Year                    Title   Revenue    Budget
0          2015                   Temper  11600000   5400000
1          2009                 Fighting  32474120
2          2009  Newtonin Moondram Vidhi
3          2012                Dark Tide    432274  25000000
4          2011                   Shakti

In [53]:
revenue_list = [row[0] for row in scraped_data_matrix]
budget_list = [row[1] for row in scraped_data_matrix]

# 2. Assign them straight to the columns based purely on position order
df_part1['Revenue'] = revenue_list
df_part1['Budget'] = budget_list
df_part1.head()

,Release_Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki_Page,Plot,Revenue,Budget
0,2015,Temper,Telugu,Puri Jagannadh,"N. T. Rama Rao Jr., Kajal Aggarwal, Prakash Raj",action,https://en.wikipedia.org/wiki/Temper_(film),Daya is an orphan who grows up learning that a...,11600000,5400000
1,2009,Fighting,American,Dito Montiel,"Channing Tatum, Terrence Howard",action,https://en.wikipedia.org/wiki/Fighting_(2009_f...,Present day New York City: Shawn MacArthur (Ch...,32474120,
2,2009,Newtonin Moondram Vidhi,Tamil,Thai Muthuselvam,"S. J. Surya, Sayali Bhagat, Rajiv Krishna\r\n",action,https://en.wikipedia.org/wiki/Newtonin_Moondra...,The film opens with a grim and bearded angry y...,,
3,2012,Dark Tide,American,John Stockwell,"Halle Berry, Olivier Martinez, Ralph Brown, Lu...",action,https://en.wikipedia.org/wiki/Dark_Tide,Kate is a shark expert whose business has been...,432274,25000000
4,2011,Shakti,Telugu,Meher Ramesh,"Jr. NTR, Ileana D'Cruz, Manjari Phadnis, Jacki...",action,https://en.wikipedia.org/wiki/Shakti_(2011_film),Aishwarya (Ileana D'Cruz) is the daughter of c...,,

In [52]:
print(scraped_data_matrix)

[['11600000', '5400000'], ['32474120', ''], ['', ''], ['432274', '25000000'], ['', ''], ['45491656', '10500000'], ['', ''], ['', ''], ['314975955', '100000000'], [None, None], ['19924033', '70000000'], ['62600000', '30000000'], ['', ''], ['52800000', '52000000'], ['', ''], ['', ''], ['', ''], ['39881', ''], ['870325439', '30100000'], ['30800000', '45000000'], ['', ''], ['', ''], ['810243', ''], ['', ''], ['', ''], ['207283925', '38000000'], ['', ''], ['', ''], ['19233280', '25000000'], ['', ''], ['716934779', '200000000'], ['', ''], ['', ''], ['', ''], ['3704408', '3500000'], ['', ''], ['', ''], ['704709660', '340000000'], ['', ''], ['', ''], ['', '6500000'], ['', ''], ['', ''], ['', ''], ['', ''], ['57777106', '66000000'], ['378858340', '150000000'], [None, None], ['', ''], ['521918', '14000000'], ['', ''], ['', ''], ['', ''], ['6282446', '10000000'], ['', ''], ['', ''], ['', ''], ['', ''], [None, None], [None, None], ['26000000', '13000000'], ['', ''], ['50000000', '850000'], ['', ''], ['34600000', '20000000'], ['', ''], ['', ''], ['', ''], ['23000000', '11000000'], ['', ''], ['71508440', '40000000'], [None, None], ['', ''], ['', ''], ['17280326', '22000000'], ['', ''], ['85416905', '35000000'], ['', ''], ['15000000', '5000000'], ['82499399', '12000000'], ['', ''], ['56681566', '43000000'], ['', '450000'], ['2500277', '20000000'], ['54744738', '94000000'], ['51386477', '70000000'], ['', ''], ['101200000', '46000000'], ['', ''], ['2010000', '730000'], ['16000000', '7000000'], ['', ''], [None, None], ['', ''], ['23510601', '24000000'], ['', ''], [None, None], ['41604473', '25000000'], ['', ''], ['120654337', '40000000'], ['', ''], ['', ''], ['', '12000000'], ['', '4000000'], [None, None], ['', ''], ['', ''], [None, None], ['10748185', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['169332978', '150000000'], ['30700000', '25000000'], ['632091832', '130000000'], ['147298761', '14500000'], ['660998756', '80000000'], ['145358062', '110000000'], ['', ''], ['1038027526', '100000000'], ['186053725', '120000000'], ['55443032', '25000000'], ['', '20000000'], [None, None], ['116755080', '51000000'], ['966550600', '175000000'], ['489676241', '60000000'], [None, None], ['8800000', '20000000'], ['109862682', '20000000'], ['55200000', '50000000'], ['332207671', '175000000'], ['', ''], ['314400000', '150000000'], ['200811689', '85000000'], ['64762724', '37000000'], ['', '35000000'], ['', ''], ['87000000', '60000000'], ['25615231', '14000000'], ['', ''], ['16426471', '11000000'], ['5380118', '5000000'], ['915840', '40000000'], ['52900000', '20000000'], ['384335608', '100000000'], ['3176880', '2000000'], ['', ''], ['177490', ''], ['69834815', '50000000'], ['135700000', '20000000'], ['408579038', '105000000'], ['461983149', '120000000'], ['15249308', '3000000'], ['343397247', '80000000'], ['521311860', '180000000'], ['118133252', '40000000'], ['80767884', '60000000'], ['', ''], ['50826898', '32000000'], ['', ''], ['102338515', '80000000'], ['122563539', '80000000'], ['6491969', '10000000'], ['44460850', '10000000'], ['62870546', '46000000'], ['2277607', ''], ['383257136', '59000000'], ['349779543', '73000000'], ['23833131', '34000000'], ['298572799', '85000000'], ['16627188', '35000000'], ['', ''], ['22783990', '7300000'], ['', ''], ['38100000', '47000000'], ['5500000', '750000'], ['603900354', '150000000'], ['7659918', '8700000'], ['13247725', '15000000'], ['95608995', '34000000'], ['', ''], ['875457937', '75000000'], ['140175006', '75000000'], ['808310187', '160000000'], ['', ''], ['', ''], ['623726000', '150000000'], ['325286646', '200000000'], ['', ''], ['', ''], ['527068851', '75000000'], ['309979994', '150000000'], ['4634032', '12800000'], ['178120010', '149000000'], ['262511490', '75000000'], ['80936232', '25000000'], ['', ''], ['3255965', '5000000'], ['579700000', '115000000'], ['141067890', '30000000'], ['3916195', ''], ['13131714', ''], ['11179372', '1500000'], ['191452', ''], ['', ''], ['', ''], ['149000000', '85000000'], ['68282844', '8500000'], ['109578115', '140000000'], ['', ''], ['287594577', '150000000'], ['50461371', ''], ['34949567', ''], ['36407407', ''], ['149660003', '23000000'], ['13219807', ''], [None, None], ['22053994', ''], ['44339362', '10000000'], [None, None], [None, None], ['41397727', ''], ['', ''], ['', ''], ['18010317', '30000000'], ['24366656', '49300000'], ['17876559', ''], ['16537336', ''], ['117932401', '30000000'], ['46180706', ''], ['67282623', '13000000'], ['20121073', '7000000'], ['7243674', ''], ['42808575', ''], ['34702573', ''], ['548192', '5000000'], ['911467', ''], [None, None], ['', ''], ['', ''], ['', ''], ['7621364', ''], ['', ''], [None, None], ['', ''], [None, None], ['', ''], ['', ''], ['', ''], ['8100000', ''], ['', ''], ['', ''], ['', ''], ['2014665', ''], ['', ''], ['10197984', ''], ['52119081', ''], ['', ''], ['3478290', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['32293377', ''], ['', ''], ['', ''], ['', ''], ['', ''], [None, None], ['7449778', ''], ['', ''], ['5816330', ''], ['7701498', '2000000'], [None, None], ['44057737', ''], ['6748888', ''], ['', ''], ['15954700', ''], [None, None], ['', ''], [None, None], ['', ''], [None, None], ['42770271', ''], ['3156482', ''], ['', ''], ['21100000', ''], ['21434003', ''], ['', ''], ['20768817', ''], ['8749681', ''], ['', ''], ['74223861', ''], [None, None], ['', ''], ['', ''], ['', ''], ['', ''], [None, None], ['', ''], ['', ''], ['22605153', '25000000'], ['29900000', '40000000'], ['105173115', '30000000'], ['15000000', '3500000'], ['', ''], ['22588876', ''], ['', '250'], ['', '3500000'], ['', ''], ['', ''], ['', ''], [None, None], ['', ''], ['103100000', '35000000'], ['', '1500000'], [None, None], ['70442940', '25000000'], [None, None], ['128100000', '65000000'], ['', ''], ['4400000', '10000000'], ['', ''], ['104003322', '64000000'], ['9458', ''], ['19351569', '22000000'], ['19322135', '40000000'], ['', ''], ['', ''], ['1328612', '800000'], [None, None], ['', ''], ['', ''], ['36351350', '25000000'], ['4280982', '4250000'], ['124914842', '45000000'], ['', ''], ['43300000', '18000000'], ['', ''], ['', ''], ['', ''], ['27699692', ''], ['615816', '3500000'], ['3300000', ''], ['', ''], ['24793509', '6500000'], ['154026136', '37000000'], ['', '3800000'], ['', ''], ['', ''], ['', ''], ['', ''], ['70000000', '9000000'], ['', ''], ['529546', ''], ['', ''], ['7704164', ''], ['55030051', '20000000'], ['', ''], ['22456509', '8500000'], ['17300000', '10000000'], ['67900000', '22000000'], ['17600000', '21000000'], ['177400000', '26000000'], ['', ''], ['', ''], ['', ''], ['53396635', '25000000'], ['63647656', '22000000'], ['', '60000000'], ['10569964', '7000000'], ['3700000', '420000'], ['64800000', '36000000'], ['', '4500000'], ['', ''], ['', ''], ['18634654', '25000000'], ['', '2000000'], ['', ''], ['', ''], ['60421', ''], ['', ''], ['13022756', '26000000'], ['', ''], ['270000000', '37000000'], ['', ''], ['49700000', '50000000'], ['8100000', '6500000'], ['11947954', '3000000'], ['230685453', '80000000'], ['', ''], ['240685326', '82500000'], ['', ''], ['199043242', '60000000'], ['', ''], ['18914307', '33000000'], ['204313400', '90000000'], ['174440724', '175000000'], ['', ''], ['', ''], ['163000000', '72500000'], ['215637183', ''], ['', ''], ['', ''], ['8742330', '7500000'], ['', ''], ['', ''], ['151831537', '15000000'], ['', ''], ['', ''], ['18618284', '30000000'], ['', ''], [None, None], ['', ''], ['', ''], ['', ''], ['', ''], ['89661', ''], [None, None], ['16443609', '21000000'], ['', ''], ['', ''], ['', ''], ['1318945', ''], ['800000', ''], ['', ''], [None, None], ['39952437', '11000000'], ['', ''], ['10522511', '700000'], ['6500000', '18500000'], ['81864', '700000'], ['77208711', '25000000'], ['3396345', '20000000'], ['', '8000000'], ['', ''], ['', ''], ['', ''], ['', ''], ['228239', ''], ['', ''], ['', ''], ['', ''], [None, None], ['28000000', '21000000'], ['30500000', '30000000'], ['234801895', '34200000'], ['265126918', '40000000'], ['', ''], ['', ''], ['', ''], ['1553826', ''], ['', ''], [None, None], ['', ''], ['24174885', '18000000'], ['', ''], ['5092129', '30000000'], ['', ''], [None, None], ['', ''], [None, None], ['', ''], ['', ''], ['1800000', '10000000'], ['15747947', ''], ['37000', '20000'], ['13585314', ''], ['49000000', '15000000'], ['', ''], ['', ''], ['', '9500'], ['', ''], ['', ''], ['17185954', '17000000'], ['', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['', ''], ['163400000', '65000000'], ['444098', '100000'], ['', ''], ['', '200000'], ['481234', '1000000'], ['', ''], ['159429', ''], ['1037335', '25000000'], ['8315', '2500000'], [None, None]]

In [54]:
df_part1.to_csv("scraped_movie_data_part1.csv", index=False)

In [ ]:
test = pd.read_csv("scraped_movie_data_part1.csv")
test.head()

(498, 10)

In [58]:
test.shape

(498, 10)

In [10]:
driver = uc.Chrome(version_main=150, options=uc.ChromeOptions())
two_df_part2 = df_part2[['Release_Year','Title']]
scraped_data_matrix = []

for row in two_df_part2.itertuples(index=False):
    release_year, title = row
    try:
        revenue, budget = get_movie_revenue_and_budget(driver,release_year,title)
    except Exception as e:
        revenue, budget = None, None
    time.sleep(5)  # Wait for 5 seconds before the next iteration
    scraped_data_matrix.append([revenue, budget])
    print(f"Scraped data for {title} ({release_year}): Revenue = {revenue}, Budget = {budget}")

driver.quit()
print("Scraping completed.")

Scraped data for Fireflies in the Garden (2008): Revenue = 6692182, Budget = 8000000
Scraped data for Aha! (2007): Revenue = , Budget =
Scraped data for The Hangman (2010): Revenue = , Budget =
Scraped data for Jamesy Boy (2014): Revenue = , Budget =
Scraped data for Funkytown (2011): Revenue = , Budget = 7300000
Scraped data for Faust (2011): Revenue = , Budget = 14400000
Scraped data for American Dreams in China (2013): Revenue = 88000000, Budget =
Scraped data for Wah Taj (2014): Revenue = None, Budget = None
Scraped data for Life Show (2002): Revenue = , Budget =
Scraped data for Chitrangada (2012): Revenue = , Budget =
Scraped data for Get on Up (2014): Revenue = 33448971, Budget = 30000000
Scraped data for 32aam adhyayam 23aam vaakyam (2015): Revenue = , Budget =
Scraped data for Changeling (2008): Revenue = 113400000, Budget = 55000000
Scraped data for Phir Kabhi (2009): Revenue = , Budget =
Scraped data for Million Dollar Arm (2014): Revenue = 38307627, Budget = 25000000
Scraped data for Jasmine Women (2004): Revenue = 640000, Budget = 2470000
Scraped data for Gabrielle (2013): Revenue = , Budget =
Scraped data for  On Line (2002): Revenue = 4500000, Budget = 16000000
Scraped data for Naanu Avanalla...Avalu (2015): Revenue = , Budget =
Scraped data for Face to Face (2011): Revenue = , Budget =
Scraped data for 50 to 1 (2014): Revenue = 1064454, Budget = 10000000
Scraped data for 3 Deewarein (2003): Revenue = , Budget =
Scraped data for Abohoman (2010): Revenue = None, Budget = None
Scraped data for Bleak Night (2011): Revenue = , Budget =
Scraped data for Same Kind of Different as Me (2017): Revenue = 6423605, Budget =
Scraped data for Baboo Band Baaja[6] (2012): Revenue = None, Budget = None
Scraped data for Spy Kids (2001): Revenue = 147934180, Budget = 35000000
Scraped data for Stuart Little 2 (2002): Revenue = 169956806, Budget = 120000000
Scraped data for Satrangee Parachute (2011): Revenue = , Budget =
Scraped data for MirrorMask (2005): Revenue = 973613, Budget = 4000000
Scraped data for Njanum Ente Familiyum (ഞാനും എന്റെ ഫാമിലിയും) (2012): Revenue = None, Budget = None
Scraped data for KL 10 Patthu (2015): Revenue = , Budget =
Scraped data for Bharya Onnu Makkal Moonnu (ഭാര്യ ഒന്നു് മക്കൾ മൂന്നു്) (2009): Revenue = None, Budget = None
Scraped data for Ice Age: Dawn of the Dinosaurs (2009): Revenue = 886686817, Budget = 90000000
Scraped data for Ringmaster (2014): Revenue = None, Budget = None
Scraped data for Because of Winn-Dixie (2005): Revenue = 32645546, Budget = 14000000
Scraped data for Njangalude Veettile Athidhikal (2014): Revenue = , Budget =
Scraped data for Scooby-Doo (2002): Revenue = 275650703, Budget = 84000000
Scraped data for Thirunakkara Perumal (തിരുനക്കര പെരുമാൾ) (2009): Revenue = None, Budget = None
Scraped data for Super Buddies (2013): Revenue = , Budget =
Scraped data for Freaky Friday (2003): Revenue = 160846332, Budget = 26000000
Scraped data for Hoot (2006): Revenue = 8200000, Budget = 15000000
Scraped data for Blizzard (2003): Revenue = , Budget =
Scraped data for Snow Dogs (2002): Revenue = 81000000, Budget = 35000000
Scraped data for Oru Small Family ( ഒരു സ്മോൾ ഫാമിലി ) (2010): Revenue = None, Budget = None
Scraped data for Saving Shiloh (2006): Revenue = , Budget =
Scraped data for Cowgirls 'n Angels (2012): Revenue = 120680, Budget =
Scraped data for Varsham (2014): Revenue = , Budget =
Scraped data for Sand City (2015): Revenue = , Budget =
Scraped data for Marupadi (2016): Revenue = , Budget =
Scraped data for Charlotte's Web (2006): Revenue = 148964660, Budget = 85000000
Scraped data for Agent Cody Banks 2: Destination London (2004): Revenue = 28818995, Budget = 26000000
Scraped data for Judy Moody and the Not Bummer Summer (2011): Revenue = 14166853, Budget = 20000000
Scraped data for Toy Story 3 (2010): Revenue = 1067316101, Budget = 200000000
Scraped data for Flicka (2006): Revenue = 21000000, Budget = 15000000
Scraped data for The Longshots (2008): Revenue = 11767866, Budget = 23000000
Scraped data for Back to the Secret Garden (2001): Revenue = None, Budget = None
Scraped data for Anumati (2013): Revenue = , Budget =
Scraped data for Elsamma Enna Aankutty ( എൽസമ്മ എന്ന ആൺകുട്ടി ) (2010): Revenue = , Budget =
Scraped data for Fat Albert (2004): Revenue = 48600000, Budget = 45000000
Scraped data for A Dog's Purpose (2017): Revenue = 205000000, Budget = 22000000
Scraped data for Bhageeratha (2005): Revenue = , Budget =
Scraped data for Kudumbasree Travels (കുടുംബശ്രീ ട്രാവൽസ്‌) (2011): Revenue = , Budget =
Scraped data for Christmas Story 2, AA Christmas Story 2 (2012): Revenue = None, Budget = None
Scraped data for 2 Penkuttikal (2016): Revenue = , Budget =
Scraped data for The Country Bears (2002): Revenue = 18012097, Budget = 35000000
Scraped data for The Perfect Holiday (2007): Revenue = 5800000, Budget =
Scraped data for Pinocchio (2002): Revenue = 41323171, Budget = 40000000
Scraped data for Bharya Athra Pora (2013): Revenue = 1051000, Budget = 580000
Scraped data for Oru Black And White Kudumbam (ഒരു ബ്ലാക്ക്‌ ആന്റ്‌ വൈറ്റ്‌ കുടുംബം) (2009): Revenue = None, Budget = None
Scraped data for Bharya Swantham Suhruthu (ഭാര്യ സ്വന്തം സുഹൃത്തു്) (2009): Revenue = , Budget =
Scraped data for  Kit Kittredge: An American Girl (2008): Revenue = 17700000, Budget = 10000000
Scraped data for Polytechnic (2014): Revenue = 1200000, Budget = 900000
Scraped data for Benji: Off the Leash! (2004): Revenue = , Budget =
Scraped data for College Road Trip (2008): Revenue = 51549674, Budget = 25000000
Scraped data for The Nativity Story (2006): Revenue = 46400000, Budget = 35000000
Scraped data for The Journey (2014): Revenue = 1021103568, Budget = 250000000
Scraped data for Firehouse Dog (2007): Revenue = 17384424, Budget =
Scraped data for The Cat in the Hat (2003): Revenue = 133800000, Budget = 109000000
Scraped data for Swantham Bharya Zindabad ( സ്വന്തം ഭാര്യ സിന്ദാബാദ്‌ ) (2010): Revenue = , Budget =
Scraped data for Akeelah and the Bee (2006): Revenue = 18948425, Budget = 8000000
Scraped data for Mr. Popper's Penguins (2011): Revenue = 187361754, Budget = 55000000
Scraped data for Akashangalil (2015): Revenue = , Budget =
Scraped data for Daddy Cool (2009): Revenue = , Budget =
Scraped data for Tekken (2009): Revenue = 226830568, Budget = 25000000
Scraped data for Final Fantasy: The Spirits Within (2001): Revenue = 85131830, Budget = 137000000
Scraped data for Mr. Magorium's Wonder Emporium (2007): Revenue = 69500000, Budget = 65000000
Scraped data for Legend of the Guardians: The Owls of Ga'Hoole (2010): Revenue = 140073390, Budget = 80000000
Scraped data for The Santa Clause 3: The Escape Clause (2006): Revenue = 84500122, Budget = 12000000
Scraped data for Cirque du Freak: The Vampire's Assistant (2009): Revenue = 28169671, Budget = 40000000
Scraped data for Charlie and the Chocolate Factory (2005): Revenue = 475000000, Budget = 150000000
Scraped data for Gadi No.305 lo Devudu (2008): Revenue = , Budget =
Scraped data for Megiddo: The Omega Code 2 (2001): Revenue = 6047691, Budget = 22000000
Scraped data for  Nanny McPhee (2005): Revenue = 123276807, Budget = 25000000
Scraped data for Malice in Wonderland (2009): Revenue = , Budget =
Scraped data for Clash of the Empires (2012): Revenue = , Budget =
Scraped data for Devi Putrudu (2001): Revenue = , Budget =
Scraped data for The Legend of Hercules (2014): Revenue = 61279452, Budget = 70000000
Scraped data for Magic Magic 3D (2003): Revenue = , Budget =
Scraped data for Warcraft (2016): Revenue = 433677183, Budget = 160000000
Scraped data for Mind Game (2004): Revenue = 36613, Budget =
Scraped data for Ambuli (2012): Revenue = , Budget =
Scraped data for Magic to Win (2011): Revenue = 8557, Budget = 8000000
Scraped data for The Boxtrolls (2014): Revenue = 108255770, Budget = 60000000
Scraped data for  Ella Enchanted (2004): Revenue = 27400000, Budget = 31000000
Scraped data for Irandaam Ulagam (2013): Revenue = , Budget = 9200000
Scraped data for Monkeybone (2001): Revenue = 5409517, Budget = 75000000
Scraped data for From Time to Time (2009): Revenue = , Budget =
Scraped data for Jack the Giant Killer (2013): Revenue = , Budget = 50000
Scraped data for Naan Ee (2012): Revenue = 19450000, Budget = 5990000
Scraped data for Into the Woods (2014): Revenue = 212902372, Budget = 50000000
Scraped data for Painted Skin: The Resurrection (2012): Revenue = 103131994, Budget =
Scraped data for Night at the Museum (2006): Revenue = 574480841, Budget = 110000000
Scraped data for How to Train Your Dragon 2 (2014): Revenue = 621537519, Budget = 145000000
Scraped data for Obhishopto Nighty (2014): Revenue = , Budget =
Scraped data for Wolfhound (2006): Revenue = 21573338, Budget = 20000000
Scraped data for She Creature (2001): Revenue = , Budget =
Scraped data for Harry Potter and the Deathly Hallows: Part I (2010): Revenue = 954305868, Budget = 250000000
Scraped data for Jade Warrior (2006): Revenue = , Budget =
Scraped data for Stranger Than Fiction (2006): Revenue = 53653224, Budget = 30000000
Scraped data for Baahubali: The Conclusion (2017): Revenue = 280700000, Budget = 31000000
Scraped data for The Water Horse: Legend of the Deep (2007): Revenue = 103967384, Budget = 40000000
Scraped data for Alice Through the Looking Glass (2016): Revenue = 299457024, Budget = 170000000
Scraped data for Sky High (2005): Revenue = 86369815, Budget = 35000000
Scraped data for Gyokairui Yamaoka Maiko (2011): Revenue = None, Budget = None
Scraped data for The Lord of the Rings: The Fellowship of the Ring (2001): Revenue = 871368364, Budget = 93000000
Scraped data for Pan's Labyrinth (2006): Revenue = 83258226, Budget = 19000000
Scraped data for Maleficent (2014): Revenue = 758539785, Budget = 180000000
Scraped data for The Medallion (2003): Revenue = 34300000, Budget = 38000000
Scraped data for Maan Karate (2014): Revenue = , Budget =
Scraped data for Osmosis Jones (2001): Revenue = 13596911, Budget = 75000000
Scraped data for Vampire Academy (2014): Revenue = 15391979, Budget = 30000000
Scraped data for Howl's Moving Castle (2004): Revenue = 236049757, Budget = 24000000
Scraped data for Aabra Ka Daabra (2004): Revenue = 236000, Budget = 1800000
Scraped data for The Piano Tuner of Earthquakes (2005): Revenue = 27953, Budget =
Scraped data for Day Watch (2006): Revenue = 42918532, Budget = 4200000
Scraped data for Eragon (2006): Revenue = 250425512, Budget = 100000000
Scraped data for The Chronicles of Narnia: Prince Caspian (2008): Revenue = 419665568, Budget = 225000000
Scraped data for Dracula Untold (2014): Revenue = 217124280, Budget = 70000000
Scraped data for An American Carol (2008): Revenue = 7000000, Budget = 20000000
Scraped data for Heartless (2009): Revenue = 20435, Budget = 5000000
Scraped data for Stardust (2007): Revenue = 137500000, Budget = 70000000
Scraped data for Seventh Son (2015): Revenue = 114178613, Budget = 95000000
Scraped data for Night Watch (2004): Revenue = , Budget = 6000000
Scraped data for Jaani Dushman: Ek Anokhi Kahani (2002): Revenue = , Budget =
Scraped data for Harry Potter and the Goblet of Fire (2005): Revenue = 895921036, Budget = 150000000
Scraped data for Barbie: The Princess and the Popstar (2012): Revenue = None, Budget = None
Scraped data for Garo: Red Requiem (2010): Revenue = , Budget =
Scraped data for Aladin (2009): Revenue = , Budget =
Scraped data for Adhisaya Ulagam (2012): Revenue = , Budget =
Scraped data for Yamadonga (2007): Revenue = 10000000, Budget = 4550000
Scraped data for 300: Rise of an Empire (2014): Revenue = 337580051, Budget = 110000000
Scraped data for Phoebe in Wonderland (2009): Revenue = 73, Budget =
Scraped data for Harry Potter and the Sorcerer's Stone (2001): Revenue = 1029374615, Budget = 125000000
Scraped data for Judas Ghost (2013): Revenue = , Budget = 300000
Scraped data for Enchanted (2007): Revenue = 340487652, Budget = 85000000
Scraped data for Just Visiting (2001): Revenue = 16200000, Budget = 35000000
Scraped data for The Seeker (2007): Revenue = 31852619, Budget = 45000000
Scraped data for Beowulf (2007): Revenue = 195735876, Budget = 160000000
Scraped data for Lord Livingstone 7000 Kandi (2015): Revenue = , Budget =
Scraped data for Magadheera (2009): Revenue = 15278500, Budget = 4583500
Scraped data for  Zathura (2005): Revenue = 65079104, Budget = 65000000
Scraped data for Nanny McPhee and the Big Bang (2010): Revenue = 93251121, Budget = 35000000
Scraped data for The Final Destination (2009): Revenue = 187384627, Budget = 40000000
Scraped data for Darna Zaroori Hai (2006): Revenue = , Budget =
Scraped data for Insidious (2011): Revenue = 100106454, Budget = 1500000
Scraped data for Aaaah (2014): Revenue = , Budget = 138
Scraped data for The Phobos (2010): Revenue = , Budget =
Scraped data for Bloody Mary (2006): Revenue = , Budget =
Scraped data for Mirrors (2008): Revenue = 72400000, Budget = 35000000
Scraped data for  Saw V (2008): Revenue = 118209778, Budget = 10800000
Scraped data for May (2003): Revenue = 264349, Budget = 500000
Scraped data for Black Christmas (2006): Revenue = 4000000, Budget = 686000
Scraped data for Automaton Transfusion (2006): Revenue = , Budget = 50000
Scraped data for Saw III (2006): Revenue = 164874275, Budget = 10000000
Scraped data for Jaganmohini (2009): Revenue = , Budget =
Scraped data for Nightmare Man (2006): Revenue = , Budget = 250000
Scraped data for Pridyider (2012): Revenue = , Budget =
Scraped data for Jwanita (2015): Revenue = , Budget =
Scraped data for Valentine (2001): Revenue = 16300000, Budget = 10000000
Scraped data for Friend Request (2016): Revenue = 10975390, Budget = 9900000
Scraped data for Beneath (2013): Revenue = 291420351, Budget = 100000000
Scraped data for Leprechaun: Origins (2014): Revenue = , Budget =
Scraped data for Puppet Master X: Axis Rising (2012): Revenue = , Budget =
Scraped data for Muck (2015): Revenue = , Budget = 250000
Scraped data for Bhoot Returns (2012): Revenue = 890000, Budget = 750000
Scraped data for Stage Fright (2014): Revenue = 7000, Budget =
Scraped data for Doom (2005): Revenue = 58100000, Budget = 60000000
Scraped data for Pizza (2014): Revenue = , Budget =
Scraped data for The Exorcism of Emily Rose (2005): Revenue = 145166804, Budget = 19000000
Scraped data for American Haunting !An American Haunting (2005): Revenue = 29612137, Budget = 14000000
Scraped data for  Scare Campaign (2016): Revenue = , Budget =
Scraped data for Driftwood (2006): Revenue = 1066555, Budget =
Scraped data for Corpse Party (2015): Revenue = , Budget =
Scraped data for Halloween (2007): Revenue = 80460948, Budget = 15000000
Scraped data for I Spit on Your Grave 2 (2013): Revenue = 678604, Budget =
Scraped data for Abandoned Mine (2013): Revenue = , Budget =
Scraped data for Raktharakshas 3D (2014): Revenue = None, Budget = None
Scraped data for Bay, TheThe Bay (2012): Revenue = , Budget =
Scraped data for We Are What We Are (2013): Revenue = 81381, Budget =
Scraped data for Exorcist: The Beginning (2004): Revenue = 78000586, Budget = 80000000
Scraped data for A Nightmare on Elm Street (2010): Revenue = 57004513, Budget = 1800000
Scraped data for  Prey (2009): Revenue = 3643652, Budget =
Scraped data for The Covenant (2006): Revenue = 37597471, Budget = 20000000
Scraped data for Danika (2006): Revenue = , Budget = 5000000
Scraped data for Dark World (2010): Revenue = 8628997, Budget = 3000000
Scraped data for Underworld (2003): Revenue = 95708457, Budget = 22000000
Scraped data for Dead Silence (2007): Revenue = 22382047, Budget = 20000000
Scraped data for Bayam Oru Payanam (2016): Revenue = , Budget =
Scraped data for The Haunting in Connecticut (2009): Revenue = 77578320, Budget = 10000000
Scraped data for Decoys (2004): Revenue = , Budget = 5000000
Scraped data for Sivi (2007): Revenue = , Budget =
Scraped data for Ghost Ship (2002): Revenue = 71142361, Budget = 35000000
Scraped data for The Death of Poe (2006): Revenue = , Budget =
Scraped data for The Park (2003): Revenue = , Budget =
Scraped data for Bones (2001): Revenue = 7316658, Budget = 10000000
Scraped data for The Ring (2002): Revenue = None, Budget = None
Scraped data for Chandramukhi (2005): Revenue = , Budget =
Scraped data for Long Time Dead (2002): Revenue = 13102295, Budget =
Scraped data for The Last Horror Movie (2003): Revenue = , Budget = 780000
Scraped data for Dog Soldiers (2002): Revenue = 3537283, Budget = 2000000
Scraped data for Dark Corners (2006): Revenue = , Budget =
Scraped data for The Hamiltons (2006): Revenue = , Budget =
Scraped data for Mumbai 125 KM 3D (2014): Revenue = None, Budget = None
Scraped data for When a Stranger Calls (2006): Revenue = 25000000, Budget = 1500000
Scraped data for Freddy vs. Jason (2003): Revenue = 116643421, Budget = 30000000
Scraped data for Lankeshwari (2011): Revenue = None, Budget = None
Scraped data for The Wolfman (2010): Revenue = 140700000, Budget = 150000000
Scraped data for Muni (2007): Revenue = , Budget =
Scraped data for  Bait 3D (2012): Revenue = 32500000, Budget = 33492566
Scraped data for Riding the Bullet (2004): Revenue = 264505, Budget = 5000000
Scraped data for Don't Be Afraid of the Dark (2011): Revenue = 36993168, Budget = 25000000
Scraped data for Gekijōban Zero (2014): Revenue = , Budget =
Scraped data for The Reaping (2007): Revenue = 62771059, Budget = 40000000
Scraped data for Agyaat (2009): Revenue = , Budget =
Scraped data for Ginger Snaps Back: The Beginning (2004): Revenue = , Budget = 3500000
Scraped data for  Tarnation (2017): Revenue = , Budget =
Scraped data for Black Cadillac (2003): Revenue = , Budget =
Scraped data for The Amityville Horror (2005): Revenue = 107516369, Budget = 19000000
Scraped data for Wild Country (2006): Revenue = , Budget = 1599411
Scraped data for Room 6 (2006): Revenue = , Budget = 1000000
Scraped data for Ao Oni (2014): Revenue = , Budget =
Scraped data for Parasyte: Part 2 (2015): Revenue = 12828829, Budget =
Scraped data for The Fog (2005): Revenue = 46201432, Budget = 18000000
Scraped data for Susuk (2008): Revenue = , Budget =
Scraped data for Final Destination 2 (2003): Revenue = 90941129, Budget = 26000000
Scraped data for Jason X (2002): Revenue = 17077882, Budget = 11000000
Scraped data for  Venom (2005): Revenue = 881779, Budget =
Scraped data for The Midnight Meat Train (2008): Revenue = 3533227, Budget = 15000000
Scraped data for Puppet Master: The Legacy (2003): Revenue = , Budget =
Scraped data for The Hills Have Eyes (2006): Revenue = 69623713, Budget = 15000000
Scraped data for Tormented (2009): Revenue = 1362653, Budget =
Scraped data for Demonte Colony (2015): Revenue = 2000000, Budget = 240000
Scraped data for Vaastu Shastra (2004): Revenue = , Budget =
Scraped data for Orphan (2009): Revenue = 77912251, Budget = 20000000
Scraped data for Lights Out (2016): Revenue = 149368835, Budget = 4900000
Scraped data for Hansel & Gretel (2013): Revenue = 226349749, Budget = 50000000
Scraped data for Jug Face (2013): Revenue = , Budget =
Scraped data for Frailty (2001): Revenue = 17400000, Budget = 11000000
Scraped data for  Van Helsing (2004): Revenue = 300257475, Budget = 160000000
Scraped data for Creep (2004): Revenue = 7480424, Budget =
Scraped data for Kotoko (2012): Revenue = , Budget =
Scraped data for Kanchana (2011): Revenue = , Budget =
Scraped data for The Tunnel (2011): Revenue = , Budget = 135000
Scraped data for Halloween: Resurrection (2002): Revenue = 37664958, Budget = 13000000
Scraped data for Ju-on: The Grudge (2003): Revenue = 3657876, Budget = 3500000
Scraped data for The Bye Bye Man (2017): Revenue = 26700000, Budget = 7400000
Scraped data for Gutterballs (2008): Revenue = , Budget =
Scraped data for Escape from Hell (2001): Revenue = None, Budget = None
Scraped data for  Queen of the Damned (2002): Revenue = 45479110, Budget = 35000000
Scraped data for Premonition (2004): Revenue = , Budget =
Scraped data for Hostel (2005): Revenue = 81979826, Budget = 4800000

In [11]:
revenue_list = [row[0] for row in scraped_data_matrix]
budget_list = [row[1] for row in scraped_data_matrix]

# 2. Assign them straight to the columns based purely on position order
df_part2['Revenue'] = revenue_list
df_part2['Budget'] = budget_list
df_part2.head()

,Release_Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki_Page,Plot,Revenue,Budget
498,2008,Fireflies in the Garden,American,Dennis Lee,"Julia Roberts, Ryan Reynolds, Willem Dafoe, Em...",drama,https://en.wikipedia.org/wiki/Fireflies_in_the...,The story moves back and forth between the ado...,6692182,8000000
499,2007,Aha!,Bangladeshi,Enamul Kabir Nirjhor,"Humayun Faridi, Tariq Anam Khan, Fazlur Rahman...",drama,https://en.wikipedia.org/wiki/Aha!_(film),Mr. Mallik (Tariq Anam Khan) lives in an about...,,
500,2010,The Hangman,Bollywood,Vishal Bhandari,"Om Puri, Shreyas Talpade, Gulshan Grover, Smit...",drama,https://en.wikipedia.org/wiki/The_Hangman_(201...,"The Hangman, starring internationally acclaime...",,
501,2014,Jamesy Boy,American,Trevor White,Spencer Lofranco\r\nMary-Louise Parker\r\nTais...,drama,https://en.wikipedia.org/wiki/Jamesy_Boy,"James Burns is in prison for selling guns, dru...",,
502,2011,Funkytown,Canadian,Daniel Roby,"Patrick Huard, Raymond Bouchard, Geneviève Bro...",drama,https://en.wikipedia.org/wiki/Funkytown_(film),"Set in Montreal during the disco era, the film...",,7300000

In [12]:
df_part2.to_csv("scraped_movie_data_part2.csv", index=False)

In [13]:
df_part2.shape

(499, 10)

In [2]:
df = pd.read_csv("wiki_movie_plots_deduped.csv")
df.shape

(34886, 8)

In [11]:
df_1980s = df[(df['Release Year'] >= 1990) & (df['Release Year'] < 2000)]
df_1980s.shape

(4468, 8)

In [12]:
driver = uc.Chrome(version_main=152, options=uc.ChromeOptions())
two_df_1980s = df_1980s[['Release Year','Title']]
scraped_data_matrix = []
count = 0
for row in two_df_1980s.itertuples(index=False):
    release_year, title = row
    try:
        revenue, budget = get_movie_revenue_and_budget(driver,release_year,title)
    except Exception as e:
        revenue, budget = None, None
    time.sleep(5)  # Wait for 5 seconds before the next iteration
    scraped_data_matrix.append([revenue, budget])
    print(f"Scraped data for {title} ({release_year}): Revenue = {revenue}, Budget = {budget}")
    count += 1
    if count == 1300:
        break
    print(f"Scraped {count} movies so far.")

driver.quit()
print("Scraping completed.")

Scraped data for The Adventures of Ford Fairlane (1990): Revenue = 20423389, Budget = 49000000
Scraped 1 movies so far.
Scraped data for After Dark, My Sweet (1990): Revenue = , Budget =
Scraped 2 movies so far.
Scraped data for Air America (1990): Revenue = 57661269, Budget = 35000000
Scraped 3 movies so far.
Scraped data for Alice (1990): Revenue = 57200000, Budget = 3000000
Scraped 4 movies so far.
Scraped data for Almost an Angel (1990): Revenue = 6939946, Budget = 25000000
Scraped 5 movies so far.
Scraped data for The Ambulance (1990): Revenue = , Budget = 4000000
Scraped 6 movies so far.
Scraped data for American Ninja 4: The Annihilation (1990): Revenue = 358047, Budget =
Scraped 7 movies so far.
Scraped data for Andre's Mother (1990): Revenue = , Budget =
Scraped 8 movies so far.
Scraped data for Angel Town (1990): Revenue = 855810, Budget = 1800000
Scraped 9 movies so far.
Scraped data for Another 48 Hrs. (1990): Revenue = 153518974, Budget = 38000000
Scraped 10 movies so far.
Scraped data for Arachnophobia (1990): Revenue = 53200000, Budget = 31000000
Scraped 11 movies so far.
Scraped data for Avalon (1990): Revenue = , Budget =
Scraped 12 movies so far.
Scraped data for Awakenings (1990): Revenue = 52096475, Budget = 31000000
Scraped 13 movies so far.
Scraped data for Back to the Future Part III (1990): Revenue = 244527583, Budget = 40000000
Scraped 14 movies so far.
Scraped data for Bad Influence (1990): Revenue = 12626043, Budget = 7000000
Scraped 15 movies so far.
Scraped data for Basket Case 2 (1990): Revenue = , Budget = 2500000
Scraped 16 movies so far.
Scraped data for Betsy's Wedding (1990): Revenue = 19740070, Budget =
Scraped 17 movies so far.
Scraped data for Bird on a Wire (1990): Revenue = 138697012, Budget = 20000000
Scraped 18 movies so far.
Scraped data for Blind Faith (1990): Revenue = None, Budget = None
Scraped 19 movies so far.
Scraped data for Bloodfist II (1990): Revenue = 1292357, Budget =
Scraped 20 movies so far.
Scraped data for Blue Steel (1990): Revenue = 8217997, Budget =
Scraped 21 movies so far.
Scraped data for The Bonfire of the Vanities (1990): Revenue = 15691192, Budget = 47000000
Scraped 22 movies so far.
Scraped data for Bride of Re-Animator (1990): Revenue = 1215, Budget = 2500000
Scraped 23 movies so far.
Scraped data for Cadence (1990): Revenue = , Budget =
Scraped 24 movies so far.
Scraped data for Cadillac Man (1990): Revenue = 27575086, Budget =
Scraped 25 movies so far.
Scraped data for Captain America (1990): Revenue = , Budget = 3000000
Scraped 26 movies so far.
Scraped data for Cartoon All-Stars to the Rescue (1990): Revenue = , Budget =
Scraped 27 movies so far.
Scraped data for Catchfire (1990): Revenue = , Budget =
Scraped 28 movies so far.
Scraped data for Challenger (1990): Revenue = , Budget =
Scraped 29 movies so far.
Scraped data for Checkered Flag (1990): Revenue = , Budget =
Scraped 30 movies so far.
Scraped data for Child's Play 2 (1990): Revenue = 35763605, Budget = 13000000
Scraped 31 movies so far.
Scraped data for China O'Brien (1990): Revenue = , Budget =
Scraped 32 movies so far.
Scraped data for Class of 1999 (1990): Revenue = 2459895, Budget = 5200000
Scraped 33 movies so far.
Scraped data for Come See the Paradise (1990): Revenue = , Budget =
Scraped 34 movies so far.
Scraped data for Coupe de Ville (1990): Revenue = 715, Budget =
Scraped 35 movies so far.
Scraped data for Crash and Burn (1990): Revenue = , Budget = 1000000
Scraped 36 movies so far.
Scraped data for Crazy People (1990): Revenue = , Budget =
Scraped 37 movies so far.
Scraped data for Cry-Baby (1990): Revenue = 8266343, Budget = 11000000
Scraped 38 movies so far.
Scraped data for Daddy's Dyin': Who's Got the Will? (1990): Revenue = 1373728, Budget =
Scraped 39 movies so far.
Scraped data for Dances with Wolves (1990): Revenue = 424208848, Budget = 22000000
Scraped 40 movies so far.
Scraped data for The Dark Side of the Moon (1990): Revenue = , Budget = 1200000
Scraped 41 movies so far.
Scraped data for Darkman (1990): Revenue = 48878502, Budget = 14000000
Scraped 42 movies so far.
Scraped data for Daughter of Darkness (1990): Revenue = , Budget =
Scraped 43 movies so far.
Scraped data for Days of Thunder (1990): Revenue = 157920733, Budget = 60000000
Scraped 44 movies so far.
Scraped data for Death Machine (1990): Revenue = None, Budget = None
Scraped 45 movies so far.
Scraped data for Decoration Day (1990): Revenue = , Budget =
Scraped 46 movies so far.
Scraped data for Def by Temptation (1990): Revenue = , Budget =
Scraped 47 movies so far.
Scraped data for Delta Force 2: The Colombian Connection (1990): Revenue = 6698361, Budget =
Scraped 48 movies so far.
Scraped data for Desperate Hours (1990): Revenue = 2742912, Budget = 18000000
Scraped 49 movies so far.
Scraped data for Dick Tracy (1990): Revenue = 103738726, Budget = 47000000
Scraped 50 movies so far.
Scraped data for Die Hard 2 (1990): Revenue = 240031094, Budget = 70000000
Scraped 51 movies so far.
Scraped data for Dorf Goes Auto Racing (1990): Revenue = , Budget =
Scraped 52 movies so far.
Scraped data for Downtown (1990): Revenue = 2346150, Budget =
Scraped 53 movies so far.
Scraped data for Dream Machine (1990): Revenue = None, Budget = None
Scraped 54 movies so far.
Scraped data for DuckTales the Movie: Treasure of the Lost Lamp (1990): Revenue = 18115724, Budget = 20000000
Scraped 55 movies so far.
Scraped data for Edward Scissorhands (1990): Revenue = 86024005, Budget = 20000000
Scraped 56 movies so far.
Scraped data for The End of Innocence (1990): Revenue = , Budget = 3500000
Scraped 57 movies so far.
Scraped data for Ernest Goes to Jail (1990): Revenue = 25029791, Budget =
Scraped 58 movies so far.
Scraped data for The Exorcist III (1990): Revenue = 39024251, Budget = 11000000
Scraped 59 movies so far.
Scraped data for Faces of Death IV (1990): Revenue = , Budget =
Scraped 60 movies so far.
Scraped data for The Final Sanction (1990): Revenue = , Budget =
Scraped 61 movies so far.
Scraped data for Fire Birds (1990): Revenue = , Budget = 22000000
Scraped 62 movies so far.
Scraped data for The First Power (1990): Revenue = 22424195, Budget = 10000000
Scraped 63 movies so far.
Scraped data for Flashback (1990): Revenue = 6488144, Budget =
Scraped 64 movies so far.
Scraped data for Flatliners (1990): Revenue = 61489265, Budget = 26000000
Scraped 65 movies so far.
Scraped data for Frankenhooker (1990): Revenue = 205068, Budget = 2500000
Scraped 66 movies so far.
Scraped data for Frankenstein Unbound (1990): Revenue = 334748, Budget = 11500000
Scraped 67 movies so far.
Scraped data for The Freshman (1990): Revenue = , Budget =
Scraped 68 movies so far.
Scraped data for Funny About Love (1990): Revenue = 8100000, Budget = 12000000
Scraped 69 movies so far.
Scraped data for Getting Lucky (1990): Revenue = None, Budget = None
Scraped 70 movies so far.
Scraped data for Ghost (1990): Revenue = 505000000, Budget = 22000000
Scraped 71 movies so far.
Scraped data for Ghost Dad (1990): Revenue = 25421633, Budget = 30000000
Scraped 72 movies so far.
Scraped data for Ghosts Can't Do It (1990): Revenue = 25000, Budget =
Scraped 73 movies so far.
Scraped data for Girlfriend from Hell (1990): Revenue = None, Budget = None
Scraped 74 movies so far.
Scraped data for The Godfather Part III (1990): Revenue = 136766062, Budget = 54000000
Scraped 75 movies so far.
Scraped data for Goodfellas (1990): Revenue = 47072327, Budget = 25000000
Scraped 76 movies so far.
Scraped data for Graffiti Bridge (1990): Revenue = , Budget = 7500000
Scraped 77 movies so far.
Scraped data for Green Card (1990): Revenue = 29888235, Budget = 12500000
Scraped 78 movies so far.
Scraped data for Gremlins 2: The New Batch (1990): Revenue = 41482207, Budget = 50000000
Scraped 79 movies so far.
Scraped data for The Grifters (1990): Revenue = 13446769, Budget =
Scraped 80 movies so far.
Scraped data for The Guardian (1990): Revenue = 17037887, Budget =
Scraped 81 movies so far.
Scraped data for Guns (1990): Revenue = 44700000, Budget = 13000000
Scraped 82 movies so far.
Scraped data for The Guyver (1990): Revenue = None, Budget = None
Scraped 83 movies so far.
Scraped data for The Handmaid's Tale (1990): Revenue = 4960385, Budget = 13000000
Scraped 84 movies so far.
Scraped data for Hard to Kill (1990): Revenue = 47410000, Budget = 10000000
Scraped 85 movies so far.
Scraped data for Hardware (1990): Revenue = 5728953, Budget = 1500000
Scraped 86 movies so far.
Scraped data for Havana (1990): Revenue = 9243140, Budget = 40000000
Scraped 87 movies so far.
Scraped data for Heart Condition (1990): Revenue = 4134992, Budget = 10000000
Scraped 88 movies so far.
Scraped data for Henry: Portrait of a Serial Killer (1990): Revenue = 609939, Budget = 111000
Scraped 89 movies so far.
Scraped data for Home Alone (1990): Revenue = 476684675, Budget = 18000000
Scraped 90 movies so far.
Scraped data for Hot Cars, Cold Facts (1990): Revenue = None, Budget = None
Scraped 91 movies so far.
Scraped data for The Hot Spot (1990): Revenue = 1293976, Budget =
Scraped 92 movies so far.
Scraped data for House Party (1990): Revenue = 26385628, Budget = 2500000
Scraped 93 movies so far.
Scraped data for The Hunt for Red October (1990): Revenue = 200512643, Budget = 30000000
Scraped 94 movies so far.
Scraped data for I Come in Peace (1990): Revenue = 9200000, Budget = 7000000
Scraped 95 movies so far.
Scraped data for I Love You to Death (1990): Revenue = , Budget =
Scraped 96 movies so far.
Scraped data for I'm Dangerous Tonight (1990): Revenue = , Budget =
Scraped 97 movies so far.
Scraped data for Initiation: Silent Night, Deadly Night 4 (1990): Revenue = , Budget =
Scraped 98 movies so far.
Scraped data for Internal Affairs (1990): Revenue = 27734391, Budget = 15000000
Scraped 99 movies so far.
Scraped data for Iron & Silk (1990): Revenue = 585174222, Budget = 140000000
Scraped 100 movies so far.
Scraped data for It (1990): Revenue = 4900000, Budget = 18000000
Scraped 101 movies so far.
Scraped data for Jacob's Ladder (1990): Revenue = 26118851, Budget = 25000000
Scraped 102 movies so far.
Scraped data for Jetsons: The Movie (1990): Revenue = , Budget =
Scraped 103 movies so far.
Scraped data for Joe Versus the Volcano (1990): Revenue = 39400000, Budget = 25000000
Scraped 104 movies so far.
Scraped data for The Kill-Off (1990): Revenue = , Budget =
Scraped 105 movies so far.
Scraped data for Killer Tomatoes Strike Back (1990): Revenue = None, Budget = None
Scraped 106 movies so far.
Scraped data for Kindergarten Cop (1990): Revenue = 201957688, Budget = 15000000
Scraped 107 movies so far.
Scraped data for King of New York (1990): Revenue = 2554712, Budget = 5300000
Scraped 108 movies so far.
Scraped data for Laser Mission (1990): Revenue = , Budget =
Scraped 109 movies so far.
Scraped data for The Last of the Finest (1990): Revenue = 1531489, Budget = 12000000
Scraped 110 movies so far.
Scraped data for Leatherface: The Texas Chainsaw Massacre III (1990): Revenue = 5765562, Budget = 2000000
Scraped 111 movies so far.
Scraped data for The Lemon Sisters (1990): Revenue = , Budget =
Scraped 112 movies so far.
Scraped data for Lionheart (1990): Revenue = 24271196, Budget = 6000000
Scraped 113 movies so far.
Scraped data for The Long Walk Home (1990): Revenue = , Budget =
Scraped 114 movies so far.
Scraped data for Look Who's Talking Too (1990): Revenue = 120889074, Budget = 12000000
Scraped 115 movies so far.
Scraped data for Loose Cannons (1990): Revenue = 5585154, Budget = 15000000
Scraped 116 movies so far.
Scraped data for Lord of the Flies (1990): Revenue = 13985225, Budget =
Scraped 117 movies so far.
Scraped data for Love at Large (1990): Revenue = 1436308, Budget =
Scraped 118 movies so far.
Scraped data for Madhouse (1990): Revenue = , Budget =
Scraped 119 movies so far.
Scraped data for Maniac Cop 2 (1990): Revenue = , Budget = 4000000
Scraped 120 movies so far.
Scraped data for Marked for Death (1990): Revenue = 46044400, Budget = 12000000
Scraped 121 movies so far.
Scraped data for Masters of Menace (1990): Revenue = , Budget =
Scraped 122 movies so far.
Scraped data for Megaville (1990): Revenue = None, Budget = None
Scraped 123 movies so far.
Scraped data for Memphis Belle (1990): Revenue = , Budget = 23000000
Scraped 124 movies so far.
Scraped data for Men at Work (1990): Revenue = 16200000, Budget = 9000000
Scraped 125 movies so far.
Scraped data for Men Don't Leave (1990): Revenue = 6070752, Budget =
Scraped 126 movies so far.
Scraped data for Men of Respect (1990): Revenue = 139155, Budget =
Scraped 127 movies so far.
Scraped data for Meridian: Kiss of the Beast (1990): Revenue = , Budget =
Scraped 128 movies so far.
Scraped data for Mermaids (1990): Revenue = 35419397, Budget = 31000000
Scraped 129 movies so far.
Scraped data for Metamorphosis: The Alien Factor (1990): Revenue = , Budget =
Scraped 130 movies so far.
Scraped data for Metropolitan (1990): Revenue = 2900000, Budget = 225000
Scraped 131 movies so far.
Scraped data for Miami Blues (1990): Revenue = 9888167, Budget = 11000000
Scraped 132 movies so far.
Scraped data for Miller's Crossing (1990): Revenue = 5080409, Budget = 14000000
Scraped 133 movies so far.
Scraped data for Misery (1990): Revenue = 61300000, Budget = 20000000
Scraped 134 movies so far.
Scraped data for Mo' Better Blues (1990): Revenue = 16153593, Budget = 10000000
Scraped 135 movies so far.
Scraped data for Mob Story (1990): Revenue = None, Budget = None
Scraped 136 movies so far.
Scraped data for A Mom for Christmas (1990): Revenue = , Budget =
Scraped 137 movies so far.
Scraped data for Moon 44 (1990): Revenue = , Budget =
Scraped 138 movies so far.
Scraped data for Mother Goose Rock 'n' Rhyme (1990): Revenue = , Budget =
Scraped 139 movies so far.
Scraped data for Mountains of the Moon (1990): Revenue = 4011793, Budget = 18000000
Scraped 140 movies so far.
Scraped data for Mr. Destiny (1990): Revenue = 15379253, Budget = 20000000
Scraped 141 movies so far.
Scraped data for Mr. and Mrs. Bridge (1990): Revenue = , Budget =
Scraped 142 movies so far.
Scraped data for My Blue Heaven (1990): Revenue = 23, Budget = 6
Scraped 143 movies so far.
Scraped data for Narrow Margin (1990): Revenue = 10900000, Budget = 17500000
Scraped 144 movies so far.
Scraped data for Navy SEALs (1990): Revenue = 25069101, Budget =
Scraped 145 movies so far.
Scraped data for The NeverEnding Story II: The Next Chapter (1990): Revenue = 16283667, Budget = 32000000
Scraped 146 movies so far.
Scraped data for Night Eyes (1990): Revenue = , Budget =
Scraped 147 movies so far.
Scraped data for Night of the Living Dead (1990): Revenue = 5835247, Budget = 4200000
Scraped 148 movies so far.
Scraped data for Nightbreed (1990): Revenue = 8862354, Budget = 11000000
Scraped 149 movies so far.
Scraped data for No Retreat, No Surrender 3: Blood Brothers (1990): Revenue = , Budget =
Scraped 150 movies so far.
Scraped data for The Nutcracker Prince (1990): Revenue = , Budget =
Scraped 151 movies so far.
Scraped data for Pacific Heights (1990): Revenue = 55000000, Budget = 18000000
Scraped 152 movies so far.
Scraped data for The Pit and the Pendulum (1990): Revenue = None, Budget = None
Scraped 153 movies so far.
Scraped data for Plunder & Lightning (1990): Revenue = , Budget =
Scraped 154 movies so far.
Scraped data for Postcards from the Edge (1990): Revenue = 39071603, Budget = 22000000
Scraped 155 movies so far.
Scraped data for Predator 2 (1990): Revenue = 57120318, Budget = 35000000
Scraped 156 movies so far.
Scraped data for Presumed Innocent (1990): Revenue = 221303188, Budget = 22000000
Scraped 157 movies so far.
Scraped data for Pretty Woman (1990): Revenue = 463406268, Budget = 14000000
Scraped 158 movies so far.
Scraped data for Problem Child (1990): Revenue = 72000000, Budget = 10000000
Scraped 159 movies so far.
Scraped data for Prom Night III: The Last Kiss (1990): Revenue = , Budget =
Scraped 160 movies so far.
Scraped data for Psycho IV: The Beginning (1990): Revenue = , Budget = 800000
Scraped 161 movies so far.
Scraped data for Pump Up the Volume (1990): Revenue = 11500000, Budget =
Scraped 162 movies so far.
Scraped data for Q&A (1990): Revenue = , Budget = 1344000
Scraped 163 movies so far.
Scraped data for Quick Change (1990): Revenue = 15260154, Budget = 15000000
Scraped 164 movies so far.
Scraped data for Quigley Down Under (1990): Revenue = 21413845, Budget =
Scraped 165 movies so far.
Scraped data for Ralph S. Mouse (1990): Revenue = None, Budget = None
Scraped 166 movies so far.
Scraped data for The Reflecting Skin (1990): Revenue = 17042, Budget =
Scraped 167 movies so far.
Scraped data for Repossessed (1990): Revenue = 1382462, Budget =
Scraped 168 movies so far.
Scraped data for The Rescuers Down Under (1990): Revenue = 47431461, Budget = 38000000
Scraped 169 movies so far.
Scraped data for Revenge (1990): Revenue = 15645616, Budget =
Scraped 170 movies so far.
Scraped data for Reversal of Fortune (1990): Revenue = 15445131, Budget =
Scraped 171 movies so far.
Scraped data for RoboCop 2 (1990): Revenue = 45681173, Budget = 35000000
Scraped 172 movies so far.
Scraped data for Robot Jox (1990): Revenue = , Budget = 10000000
Scraped 173 movies so far.
Scraped data for Rock 'n' Roll High School Forever (1990): Revenue = None, Budget = None
Scraped 174 movies so far.
Scraped data for Rocky V (1990): Revenue = 119946358, Budget = 42000000
Scraped 175 movies so far.
Scraped data for Roller Coaster Rabbit (1990): Revenue = , Budget =
Scraped 176 movies so far.
Scraped data for The Rookie (1990): Revenue = 21600000, Budget = 10000000
Scraped 177 movies so far.
Scraped data for Rosencrantz & Guildenstern Are Dead (1990): Revenue = 805104, Budget = 2500000
Scraped 178 movies so far.
Scraped data for The Russia House (1990): Revenue = 22997992, Budget = 21800000
Scraped 179 movies so far.
Scraped data for Shipwrecked (1990): Revenue = 15024232, Budget = 8500000
Scraped 180 movies so far.
Scraped data for A Shock to the System (1990): Revenue = , Budget =
Scraped 181 movies so far.
Scraped data for A Show of Force (1990): Revenue = , Budget =
Scraped 182 movies so far.
Scraped data for The Shrimp on the Barbie (1990): Revenue = , Budget = 5500000
Scraped 183 movies so far.
Scraped data for Sibling Rivalry (1990): Revenue = 17854933, Budget = 16000000
Scraped 184 movies so far.
Scraped data for Side Out (1990): Revenue = , Budget =
Scraped 185 movies so far.
Scraped data for Slumber Party Massacre 3 (1990): Revenue = , Budget =
Scraped 186 movies so far.
Scraped data for Sorority House Massacre 2 (1990): Revenue = , Budget =
Scraped 187 movies so far.
Scraped data for Snake Eater II: The Drug Buster (1990): Revenue = , Budget =
Scraped 188 movies so far.
Scraped data for Solar Crisis (1990): Revenue = , Budget = 55000000
Scraped 189 movies so far.
Scraped data for Soultaker (1990): Revenue = , Budget =
Scraped 190 movies so far.
Scraped data for Spaced Invaders (1990): Revenue = 15369573, Budget = 3000000
Scraped 191 movies so far.
Scraped data for Spirit of '76 (1990): Revenue = , Budget =
Scraped 192 movies so far.
Scraped data for Spontaneous Combustion (1990): Revenue = None, Budget = None
Scraped 193 movies so far.
Scraped data for Stanley & Iris (1990): Revenue = , Budget =
Scraped 194 movies so far.
Scraped data for State of Grace (1990): Revenue = 1911542, Budget = 7000000
Scraped 195 movies so far.
Scraped data for Stella (1990): Revenue = 20240128, Budget =
Scraped 196 movies so far.
Scraped data for Strike It Rich (1990): Revenue = , Budget =
Scraped 197 movies so far.
Scraped data for Taking Care of Business (1990): Revenue = 20000000, Budget = 14000000
Scraped 198 movies so far.
Scraped data for Tales from the Darkside: The Movie (1990): Revenue = 16324573, Budget = 3500000
Scraped 199 movies so far.
Scraped data for Teenage Mutant Ninja Turtles (1990): Revenue = 201965915, Budget = 13500000
Scraped 200 movies so far.

In [16]:
revenue_list = [row[0] for row in scraped_data_matrix]
budget_list = [row[1] for row in scraped_data_matrix]

# 2. Assign them straight to the columns based purely on position order
temp_df = pd.DataFrame({
    'revenue': revenue_list,
    'budget': budget_list
})
temp_df.shape

(1300, 2)

In [17]:
temp_df.to_csv("scraped_movie_data_1980s.csv", index=False)